/**
 * Flow G — NEW production owner-advice runtime, proven in the browser.
 *
 * The whole-business plan card on /owner is generated by the production owner-advice runtime
 * (runOwnerAdvice + buildOwnerDomainProviders) reading REAL persisted records for the seeded owner
 * business. This spec logs in as the real OWNER, opens /owner against the real seeded postgres
 * backend (no mock route), and asserts the new runtime's output renders end-to-end: top priority,
 * dominant constraint, next best action, do-not-do/stop, owner-workload/offload, proof, reassessment,
 * growth/scale gate, cross-domain arbitration, critical/red domains, stored-learning provenance and
 * the provider-backed data indicator — desktop, on reload, and on a mobile viewport.
 */
import { test, expect, type Page } from "@playwright/test";
import { authenticateUser, waitForPageReady } from "./helpers";
import { E2E_OWNER } from "./e2e-fixtures";

async function expectWholeBusinessPlan(page: Page) {
  const panel = page.locator('[data-testid="owner-whole-business-plan"]');
  await expect(panel).toBeVisible();

  // Top priority + dominant constraint from the runtime arbitration.
  await expect(panel.locator('[data-testid="wbp-top-priority"]')).toBeVisible();
  await expect(panel.locator('[data-testid="wbp-dominant-constraint"]')).not.toBeEmpty();

  // Core decision fields.
  await expect(panel.locator('[data-testid="wbp-next-action"]')).toContainText(/\w+/);
  await expect(panel.locator('[data-testid="wbp-do-not-do"]')).toContainText(/do not|stop|blocked/i);
  await expect(panel.locator('[data-testid="wbp-owner-workload"]')).toContainText(/owner workload|offload|delegate/i);
  await expect(panel.locator('[data-testid="wbp-proof"]')).toContainText(/proof/i);
  await expect(panel.locator('[data-testid="wbp-reassessment"]')).toContainText(/reassess/i);
  await expect(panel.locator('[data-testid="wbp-growth-gate"]')).toContainText(/growth|scale/i);
  await expect(panel.locator('[data-testid="wbp-arbitration"]')).toContainText(/arbitration|wins|rejected/i);
  await expect(panel.locator('[data-testid="wbp-domains"]')).toContainText(/domain/i);

  // Stored learning provenance + provider-backed data indicator (REAL persisted state).
  await expect(panel.locator('[data-testid="wbp-learning"]')).toContainText(/stored learning applied:\s*yes/i);
  await expect(panel.locator('[data-testid="wbp-provider-status"]')).toContainText(/provider-backed data/i);
  await expect(panel.locator('[data-testid="wbp-confidence"]')).toContainText(/confidence/i);
}

test.describe("G — Whole-business plan from the new runtime (real data, server-enforced)", () => {
  test("renders the new runtime's whole-business plan end-to-end", async ({ page }) => {
    const apiCalls: string[] = [];
    page.on("request", (r) => {
      const u = new URL(r.url());
      if (u.pathname.startsWith("/api/")) apiCalls.push(u.pathname);
    });
    const consoleErrors: string[] = [];
    page.on("console", (m) => { if (m.type() === "error") consoleErrors.push(m.text()); });

    await authenticateUser(page, E2E_OWNER.email, E2E_OWNER.password);
    await page.goto("/owner", { waitUntil: "networkidle" });
    await waitForPageReady(page);

    await expectWholeBusinessPlan(page);

    // The page actually called the NEW governed runtime route (not a mock).
    await page.waitForLoadState("networkidle");
    expect(apiCalls.some((p) => p.startsWith("/api/owner/whole-business-plan"))).toBe(true);
    expect(apiCalls.some((p) => p.includes("/mock"))).toBe(false);

    // No fatal client-side exception on the critical flow.
    await expect(page.locator("body")).not.toContainText(/Application error: a client-side exception/i);
    const fatal = consoleErrors.filter((e) => /Cannot read|is not a function|Hydration failed/i.test(e));
    expect(fatal, `fatal console errors: ${fatal.join(" | ")}`).toEqual([]);

    // Reload preserves the runtime-rendered state.
    await page.reload({ waitUntil: "networkidle" });
    await waitForPageReady(page);
    await expectWholeBusinessPlan(page);
  });

  test("renders the whole-business runtime summary on a mobile viewport", async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 812 });
    await authenticateUser(page, E2E_OWNER.email, E2E_OWNER.password);
    await page.goto("/owner", { waitUntil: "networkidle" });
    await waitForPageReady(page);

    const panel = page.locator('[data-testid="owner-whole-business-plan"]');
    await expect(panel).toBeVisible();
    await expect(panel.locator('[data-testid="wbp-top-priority"]')).toBeVisible();
    await expect(panel.locator('[data-testid="wbp-next-action"]')).toContainText(/\w+/);
  });
});
