-- NOTE: operator_items table creation moved to 20260428_add_asymmetric_signature
-- to ensure the table exists before ALTER operations in that migration.
-- This migration is intentionally empty to preserve migration history.
