/**
 * Owner Finance (Module 2 Slice 4) — deterministic recommendations.
 *
 * Pure: maps Slice 3 finance `OwnerFinding`s → traceable `FinanceRecommendation`s.
 * Every recommendation carries its source metric/value/threshold, severity,
 * expected impact, confidence, the required owner action, and how to verify it.
 * A finding with no template produces no recommendation (it is reported as a
 * missing action input by the planner) — nothing is invented.
 */
import type { OwnerFinding, OwnerSeverity } from "@/domain/owner-spine/contracts";
import { clampScore, clampConfidence } from "@/domain/owner-spine/contracts";
import { IMPORTANT_FIELD_LABELS } from "./data-confidence";

export interface FinanceRecommendation {
  recommendationCode: string;
  findingCode: string;
  category: string;
  sourceMetric: string;
  sourceValue: number | null;
  threshold: number | null;
  severity: OwnerSeverity;
  expectedFinancialImpactScore: number; // 0..100
  urgencyScore: number; // 0..100 (carried from the finding)
  confidence: number; // 0..1
  requiredOwnerAction: string;
  verificationMetric: string;
  verificationMethod: string;
  expectedTimeframeDays: number;
  effortScore: number; // 0..100
  ownerRole: string;
  title: string;
  evidence: string[];
}

interface FinanceRecTemplate {
  recommendationCode: string;
  category: string;
  title: string;
  requiredOwnerAction: string;
  verificationMethod: string;
  expectedTimeframeDays: number;
  effortScore: number;
  ownerRole: string;
}

/** What each IMPORTANT_FIELD unlocks in the current engine (for actionable guidance text). */
const DATA_QUALITY_FIELD_UNLOCKS: Record<string, string> = {
  receivables: "a clearer view of how much customer debt is tying up your cash",
  payables: "a clearer view of what you owe suppliers and the pressure this puts on cash",
  discountAmount: "whether discounts are eating into your profit",
  refundAmount: "whether refunds and quality problems are eating into your profit",
  costOfGoodsOrServices: "how much profit is left after the direct cost of what you sell",
  loanEmiDebtPayments: "how much of your sales are being used for loan repayments",
  salaryPayroll: "how much of your sales are being used for payroll",
  fixedCosts: "how heavily fixed costs are weighing on the business and where break-even sits",
  ownerWithdrawals: "whether owner withdrawals are putting pressure on business cash",
  orderCount: "how much profit the business makes per order",
  customerCount: "how much profit the business makes per customer",
};

/** Confidence added per IMPORTANT_FIELD supplied (mirrors calculateDataConfidence penalty). */
const CONFIDENCE_STEP_PER_FIELD = 5;

/** Confidence gate above which the survival-state assessment stops defaulting to WATCH. */
const SURVIVAL_STATE_CONFIDENCE_GATE = 70;

/**
 * Build a prioritised, context-aware owner action for FIN_OPP_DATA_QUALITY.
 *
 * `missingFields` is the priority-ordered list of field keys from the finding's
 * `missingData` array (generated by opportunity-rules.ts). `currentConfidence` is
 * the current dataConfidenceScore (0..100). Returns a plain-English instruction
 * that names the top-priority inputs, explains what they unlock, projects the
 * confidence improvement, and explicitly defers lower-priority fields so the owner
 * is not overloaded with a flat list.
 */
function buildDataQualityOwnerAction(missingFields: string[], currentConfidence: number | null): string {
  if (missingFields.length === 0) {
    return "Refresh the finance snapshot with current-period data to maintain diagnosis accuracy.";
  }

  const conf =
    typeof currentConfidence === "number" && Number.isFinite(currentConfidence) ? currentConfidence : 60;

  const label = (f: string): string => IMPORTANT_FIELD_LABELS[f] ?? f;
  const unlocks = (f: string): string | undefined => DATA_QUALITY_FIELD_UNLOCKS[f];

  const priority1 = missingFields[0];
  const priority2 = missingFields.length >= 2 ? missingFields[1] : undefined;
  const priority3 = missingFields.length >= 3 ? missingFields[2] : undefined;
  const topCount = priority2 !== undefined ? 2 : 1;
  const deferred = missingFields.slice(priority3 !== undefined ? 3 : topCount);

  const parts: string[] = [];

  // Primary action (top 1–2 fields)
  if (priority2 !== undefined) {
    const whyParts = [unlocks(priority1), unlocks(priority2)].filter(Boolean).join("; ");
    parts.push(
      `Enter ${label(priority1)} and ${label(priority2)} first` +
        (whyParts ? ` — these unlock ${whyParts}` : "") +
        `. If either does not apply to your business, enter 0 explicitly rather than leaving it blank.`
    );
  } else {
    const why = unlocks(priority1);
    parts.push(
      `Enter ${label(priority1)}` +
        (why ? ` — this unlocks ${why}` : "") +
        `. If it does not apply, enter 0 explicitly rather than leaving it blank.`
    );
  }

  // Confidence projection
  const projectedConf = Math.min(100, conf + topCount * CONFIDENCE_STEP_PER_FIELD);
  const crossesGate =
    conf < SURVIVAL_STATE_CONFIDENCE_GATE && projectedConf >= SURVIVAL_STATE_CONFIDENCE_GATE;
  if (crossesGate) {
    parts.push(
      `Adding ${topCount === 1 ? "this field" : "these two fields"} raises your diagnosis confidence from ${conf} to ${projectedConf}, which gives OpsIQ enough information to make a fuller Safe/Watch assessment.`
    );
  } else {
    parts.push(`This raises your diagnosis confidence from ${conf} to ${projectedConf}.`);
  }

  // Secondary (third field) — present as "then" without burying the primary
  if (priority3 !== undefined) {
    const thirdWhy = unlocks(priority3);
    parts.push(
      `${label(priority3)} is the next useful input after that` +
        (thirdWhy ? ` — it unlocks ${thirdWhy}` : "") +
        `.`
    );
  }

  // Deferred fields — explicit anti-overload message
  if (deferred.length > 0) {
    parts.push(
      `Do not spend time entering ${deferred.map(label).join(", ")} yet — they add lower diagnostic value at this stage.`
    );
  }

  return parts.join(" ");
}

/**
 * Finding code → recommendation template. Categories include the required set:
 * stop/reduce leakage, collect receivables, reduce debt pressure, reduce fixed
 * cost burden, reduce payroll burden, reach break-even, improve margin, improve
 * data quality, improve revenue quality (plus preserve-cash + manage-payables).
 */
export const FINANCE_REC_TEMPLATES: Record<string, FinanceRecTemplate> = {
  FIN_NEGATIVE_GROSS_MARGIN: {
    recommendationCode: "FINREC_IMPROVE_MARGIN",
    category: "improve_margin",
    title: "Make each sale profitable",
    requiredOwnerAction: "Raise your prices, or lower what it costs you to make or deliver what you sell, so your sales bring in more than the direct cost of what you sell.",
    verificationMethod: "Next period, work out gross margin again (sales minus the direct cost of what you sold, as a % of sales). Target: above 0%.",
    expectedTimeframeDays: 30,
    effortScore: 60,
    ownerRole: "owner",
  },
  FIN_NEGATIVE_NET_MARGIN: {
    recommendationCode: "FINREC_IMPROVE_MARGIN",
    category: "improve_margin",
    title: "Return the business to net profit",
    requiredOwnerAction: "Your costs are currently higher than your sales. Increase your sales, cut your costs, or do both, until what you earn is more than what you spend.",
    verificationMethod: "Next period, work out net margin again (profit left after all costs, as a % of sales). Target: above 0%.",
    expectedTimeframeDays: 30,
    effortScore: 70,
    ownerRole: "owner",
  },
  FIN_BELOW_BREAK_EVEN: {
    recommendationCode: "FINREC_REACH_BREAK_EVEN",
    category: "reach_break_even",
    title: "Reach break-even",
    requiredOwnerAction: "Your sales are below the amount you need just to cover your costs (your break-even amount). Increase sales or reduce fixed costs until sales reach that amount.",
    verificationMethod: "Next period, compare your total sales with your break-even amount (the sales needed to cover your costs). Target: sales at or above it.",
    expectedTimeframeDays: 30,
    effortScore: 60,
    ownerRole: "owner",
  },
  FIN_INSOLVENT_RUNWAY: {
    recommendationCode: "FINREC_PRESERVE_CASH_NOW",
    category: "preserve_cash",
    title: "Preserve cash immediately",
    requiredOwnerAction: "Your cash is very close to running out. Stop or postpone spending that is not essential. If customers owe you money, ask them to pay as soon as possible. Find ways to bring cash in quickly.",
    verificationMethod: "Check cash runway again (how many days your cash will last at your current spending). Target: above the danger level that triggered this advice.",
    expectedTimeframeDays: 7,
    effortScore: 50,
    ownerRole: "owner",
  },
  FIN_LOW_RUNWAY: {
    recommendationCode: "FINREC_EXTEND_RUNWAY",
    category: "preserve_cash",
    title: "Extend cash runway",
    requiredOwnerAction: "Spend less each month and, if customers owe you money, ask them to pay sooner, so your cash lasts more days.",
    verificationMethod: "Check cash runway again (how many days your cash will last at your current spending). Target: above the limit that triggered this advice.",
    expectedTimeframeDays: 14,
    effortScore: 50,
    ownerRole: "owner",
  },
  FIN_LOW_ABSOLUTE_CASH: {
    recommendationCode: "FINREC_PROTECT_LIQUID_CASH",
    category: "preserve_cash",
    title: "Build at least 2 weeks of operating cash in liquid reserves",
    requiredOwnerAction: "Postpone spending you can do without. If customers owe you money, ask them to pay sooner. Build up the cash you hold (cash in hand plus bank) until it would cover at least 14 days of all your running costs.",
    verificationMethod: "Next month, work out how many days of your costs your cash would cover. Target: more than 14 days.",
    expectedTimeframeDays: 14,
    effortScore: 45,
    ownerRole: "owner",
  },
  FIN_HIGH_FIXED_COST_BURDEN: {
    recommendationCode: "FINREC_REDUCE_FIXED_COST",
    category: "reduce_fixed_cost_burden",
    title: "Right-size fixed costs",
    requiredOwnerAction: "Review the costs that stay broadly the same even when sales change, such as rent and ongoing contracts. Ask for better terms where possible and reduce fixed costs you can safely do without.",
    verificationMethod: "Next period, work out your fixed costs as a % of sales again. Target: below the limit that triggered this advice.",
    expectedTimeframeDays: 45,
    effortScore: 60,
    ownerRole: "owner",
  },
  FIN_HIGH_PAYROLL_BURDEN: {
    recommendationCode: "FINREC_REDUCE_PAYROLL_BURDEN",
    category: "reduce_payroll_burden",
    title: "Align payroll to output",
    requiredOwnerAction: "Match staffing to demand and raise productivity per wage.",
    verificationMethod: "Re-measure payrollBurdenPct next period; target below threshold.",
    expectedTimeframeDays: 45,
    effortScore: 60,
    ownerRole: "owner",
  },
  FIN_HIGH_DEBT_PRESSURE: {
    recommendationCode: "FINREC_REDUCE_DEBT_PRESSURE",
    category: "reduce_debt_pressure",
    title: "Reduce debt-service pressure",
    requiredOwnerAction: "Restructure or prepay high-cost debt to lower EMI outflow.",
    verificationMethod: "Re-measure debtServicePressurePct next period; target below threshold.",
    expectedTimeframeDays: 45,
    effortScore: 55,
    ownerRole: "owner",
  },
  FIN_HIGH_RECEIVABLES: {
    recommendationCode: "FINREC_COLLECT_RECEIVABLES",
    category: "collect_receivables",
    title: "Collect overdue receivables",
    requiredOwnerAction: "Make a list of customers who still owe you money. Contact them and ask when they can pay.",
    verificationMethod: "Next period, work out the money customers owe you as a % of your sales again. Target: below the limit that triggered this advice.",
    expectedTimeframeDays: 14,
    effortScore: 30,
    ownerRole: "owner",
  },
  FIN_HIGH_PAYABLES: {
    recommendationCode: "FINREC_MANAGE_PAYABLES",
    category: "manage_payables",
    title: "Sequence and renegotiate payables",
    requiredOwnerAction: "Ask suppliers whether they can give you longer to pay. Review the supplier bills you owe and decide which are most important to keeping normal business operations running.",
    verificationMethod: "Next period, work out the money you owe suppliers as a % of your sales again. Target: below the limit that triggered this advice.",
    expectedTimeframeDays: 21,
    effortScore: 35,
    ownerRole: "owner",
  },
  FIN_DISCOUNT_LEAKAGE: {
    recommendationCode: "FINREC_REDUCE_LEAKAGE",
    category: "stop_reduce_leakage",
    title: "Tighten discounting",
    requiredOwnerAction: "Decide the biggest discount your staff may give without asking you, and require your approval before anyone goes above it.",
    verificationMethod: "Next period, work out the discounts you gave as a % of your sales again. Target: below the limit that triggered this advice.",
    expectedTimeframeDays: 21,
    effortScore: 30,
    ownerRole: "owner",
  },
  FIN_REFUND_REWORK_LEAKAGE: {
    recommendationCode: "FINREC_REDUCE_LEAKAGE",
    category: "stop_reduce_leakage",
    title: "Cut refunds and rework",
    requiredOwnerAction: "Go through your recent refunds and redone work. Write down why each one happened, then start fixing the reason that appears most often.",
    verificationMethod: "Next period, work out refunds, redone work and complaint-related costs as a % of your sales again. Target: lower than this period.",
    expectedTimeframeDays: 30,
    effortScore: 45,
    ownerRole: "owner",
  },
  FIN_INVALID_CURRENCY: {
    recommendationCode: "FINREC_FIX_CURRENCY",
    category: "improve_data_quality",
    title: "Set a valid reporting currency",
    requiredOwnerAction: "Enter your currency as a letter code, such as INR or USD (3 to 8 letters), in your finance snapshot.",
    verificationMethod: "On your next finance snapshot, confirm OpsIQ accepts the currency as valid.",
    expectedTimeframeDays: 3,
    effortScore: 10,
    ownerRole: "owner",
  },
  FIN_MISSING_CRITICAL_DATA: {
    recommendationCode: "FINREC_IMPROVE_DATA_QUALITY",
    category: "improve_data_quality",
    title: "Provide missing financial inputs",
    requiredOwnerAction: "Enter the listed missing inputs to raise diagnosis confidence.",
    verificationMethod: "Re-measure dataConfidenceScore next snapshot; target higher.",
    expectedTimeframeDays: 7,
    effortScore: 20,
    ownerRole: "owner",
  },
  FIN_OPP_MARGIN_IMPROVEMENT: {
    recommendationCode: "FINREC_IMPROVE_MARGIN",
    category: "improve_margin",
    title: "Lift net margin toward the healthy bar",
    requiredOwnerAction: "Review what you charge and what it costs you to deliver each sale. Raise prices or lower costs where a sale is not leaving enough profit.",
    verificationMethod: "Next period, work out net margin again (profit left after all costs, as a % of sales). Target: reach the healthy level OpsIQ compares you against.",
    expectedTimeframeDays: 45,
    effortScore: 55,
    ownerRole: "owner",
  },
  FIN_OPP_BREAK_EVEN_RECOVERY: {
    recommendationCode: "FINREC_REACH_BREAK_EVEN",
    category: "reach_break_even",
    title: "Close the gap to break-even",
    requiredOwnerAction: "Your sales are below the amount needed to cover your costs. Increase sales or reduce fixed costs until you close that gap.",
    verificationMethod: "Next period, compare your total sales with your break-even amount. Target: sales at or above it.",
    expectedTimeframeDays: 30,
    effortScore: 55,
    ownerRole: "owner",
  },
  FIN_OPP_RECEIVABLES_COLLECTION: {
    recommendationCode: "FINREC_COLLECT_RECEIVABLES",
    category: "collect_receivables",
    title: "Convert receivables to cash",
    requiredOwnerAction: "Make a list of customers who still owe you money. Contact them and ask when they can pay.",
    verificationMethod: "Next period, work out the money customers owe you as a % of your sales again. Target: lower than this period.",
    expectedTimeframeDays: 14,
    effortScore: 30,
    ownerRole: "owner",
  },
  FIN_OPP_DEBT_REDUCTION: {
    recommendationCode: "FINREC_REDUCE_DEBT_PRESSURE",
    category: "reduce_debt_pressure",
    title: "Lower debt-service pressure",
    requiredOwnerAction: "Restructure or prepay high-cost debt.",
    verificationMethod: "Re-measure debtServicePressurePct next period; target lower.",
    expectedTimeframeDays: 45,
    effortScore: 55,
    ownerRole: "owner",
  },
  FIN_OPP_LEAKAGE_REDUCTION: {
    recommendationCode: "FINREC_REDUCE_LEAKAGE",
    category: "stop_reduce_leakage",
    title: "Recover margin from cost leakage",
    requiredOwnerAction: "Give fewer discounts, and reduce refunds and redone work, so you keep more of what you sell.",
    verificationMethod: "Next period, work out discounts, refunds, redone work and complaint-related costs together as a % of your sales again. Target: lower than this period.",
    expectedTimeframeDays: 30,
    effortScore: 35,
    ownerRole: "owner",
  },
  FIN_OPP_REVENUE_QUALITY: {
    recommendationCode: "FINREC_IMPROVE_REVENUE_QUALITY",
    category: "improve_revenue_quality",
    title: "Improve revenue quality",
    requiredOwnerAction: "Diversify revenue and reduce discount dependence/concentration.",
    verificationMethod: "Re-measure revenueQualityScore next period; target higher.",
    expectedTimeframeDays: 60,
    effortScore: 50,
    ownerRole: "owner",
  },
  FIN_OPP_DATA_QUALITY: {
    recommendationCode: "FINREC_IMPROVE_DATA_QUALITY",
    category: "improve_data_quality",
    title: "Improve data completeness",
    requiredOwnerAction: "Supply the missing/stale inputs to sharpen the diagnosis.",
    verificationMethod: "Re-measure dataConfidenceScore next snapshot; target higher.",
    expectedTimeframeDays: 7,
    effortScore: 20,
    ownerRole: "owner",
  },
  FIN_NOTABLE_OUTSTANDING_DEBT: {
    recommendationCode: "FINREC_ENTER_DEBT_REPAYMENT",
    category: "reduce_debt_pressure",
    title: "Enter monthly loan repayment amount",
    requiredOwnerAction: "Enter your monthly loan repayment (the fixed amount you pay each month, often called an EMI) in the finance snapshot. If there is no fixed monthly repayment schedule, enter 0 explicitly so OpsIQ can correctly treat your monthly repayment as zero.",
    verificationMethod: "On your next finance snapshot, confirm OpsIQ can work out your debt repayment pressure (monthly repayments compared with your sales).",
    expectedTimeframeDays: 7,
    effortScore: 10,
    ownerRole: "owner",
  },
};

/** Build a traceable recommendation from a finding, or null if no template. */
export function buildFinanceRecommendation(finding: OwnerFinding): FinanceRecommendation | null {
  const tpl = FINANCE_REC_TEMPLATES[finding.code];
  if (!tpl) return null;

  // FIN_OPP_DATA_QUALITY: build a prioritised, context-aware action from the
  // missingData field keys so the owner knows exactly which inputs to enter first.
  const requiredOwnerAction =
    finding.code === "FIN_OPP_DATA_QUALITY" && finding.missingData.length > 0
      ? buildDataQualityOwnerAction(finding.missingData, finding.sourceValue ?? null)
      : tpl.requiredOwnerAction;

  return {
    recommendationCode: tpl.recommendationCode,
    findingCode: finding.code,
    category: tpl.category,
    sourceMetric: finding.sourceMetric,
    sourceValue: finding.sourceValue ?? null, // never invented
    threshold: finding.threshold ?? null,
    severity: finding.severity,
    expectedFinancialImpactScore: clampScore(finding.impactScore),
    urgencyScore: clampScore(finding.urgencyScore),
    confidence: clampConfidence(finding.confidence),
    requiredOwnerAction,
    verificationMetric: finding.verificationMetric ?? finding.sourceMetric,
    verificationMethod: tpl.verificationMethod,
    expectedTimeframeDays: tpl.expectedTimeframeDays,
    effortScore: clampScore(tpl.effortScore),
    ownerRole: tpl.ownerRole,
    title: tpl.title,
    evidence: finding.evidence,
  };
}

/** Build recommendations for every finding that has a template (in input order). */
export function buildFinanceRecommendations(findings: OwnerFinding[]): FinanceRecommendation[] {
  const recs: FinanceRecommendation[] = [];
  for (const f of findings) {
    const r = buildFinanceRecommendation(f);
    if (r) recs.push(r);
  }
  return recs;
}
