/**
 * Real-World Chaos Case Pack — seed library (packs A–L), encoded machine-readable.
 *
 * These preserve the business reality, operational mess, financial constraints, local context and
 * hidden root-cause logic from the source pack. The expansion generator (expansion.ts) derives
 * 200+ variants from these while preserving each seed's invariants and sourceSeedCaseId.
 */
import type { BehavioralCase, CaseFlags } from "./schema";
import { LOCATIONS, type LocationKey } from "./locations";

type Seed = Omit<BehavioralCase, "location" | "flags"> & {
  locationKey: LocationKey;
  flags?: Partial<CaseFlags>;
};

const FLAGS = (f: Partial<CaseFlags> = {}): CaseFlags => ({
  hostile: false, missingOrStaleData: false, cashRisk: false, capacityRisk: false,
  complianceRisk: false, ownerEmotional: false, remoteOwner: false, multiBranch: false, ...f,
});

function mk(seed: Seed): BehavioralCase {
  const { locationKey, flags, ...rest } = seed;
  return { ...rest, location: LOCATIONS[locationKey], flags: FLAGS(flags) };
}

const A = (id: string, p: Omit<Seed, "id" | "sourceSeedCaseId">): Seed => ({ id, sourceSeedCaseId: id, ...p });

export const SEED_CASES: BehavioralCase[] = [
  // ── Pack A — Laundry / dry cleaning / commercial laundry ──
  mk(A("A1", {
    title: "Kolkata neighborhood laundry — high revenue but no cash",
    archetype: "laundry_dry_cleaning", businessType: "Franchise laundry/dry-cleaning store",
    decisionCategory: "cash_margin_working_capital", locationKey: "kolkata",
    ownerGoal: "Grow the store; owner thinks rising sales means it is time to spend on marketing",
    messyFacts: [
      "Gross sales rose ₹1.8L → ₹3.2L/month but bank cash is only ₹38,000",
      "Owner gives 20–30% discounts to acquire customers; repeat customers dropping",
      "Complaints up: late delivery, missing socks, ironing marks; rework rising",
      "Owner wants to spend ₹75,000 on a hoarding and hire another delivery rider",
    ],
    numbers: { grossSalesPrev: 180000, grossSalesNow: 320000, cash: 38000, rent: 25000, electricity: 18000, water: 8000, chemicals: 12000, staff: 52000, plannedHoarding: 75000, discountPct: "20-30%" },
    hiddenRootCause: "Growth is discount-led and operationally unstable; rework + lost garments eat margin; cash trapped in receivables/refunds (no batch tracking)",
    temptingBadDecision: "Spend ₹75k on marketing + hire a rider because revenue is up",
    correctExpertDecision: "Pause broad marketing; fix quality/rework/lost-item process; compute contribution margin by service; cut blanket discounts; recover receivables/refunds; add proof-based order tracking before hiring",
    opsiqShouldSay: [
      "Revenue is up but cash and margin are worsening — do not treat growth as success",
      "Fix quality/rework and compute contribution margin by service first",
      "Reduce blanket discounting and recover receivables/refunds",
    ],
    opsiqShouldBlock: ["New marketing spend until quality and margin pass", "Hiring a rider without delivery-bottleneck proof"],
    proofRequired: ["Daily order ageing", "Complaint log", "Rework count", "Refund/lost-item value", "Contribution margin by service"],
    reassessmentTrigger: "14 days: complaint rate, repeat rate, cash balance, gross margin",
    learningRuleIfFails: "If OpsIQ approved marketing/hiring on rising revenue with falling cash/margin, store a do-not-repeat rule: revenue growth with deteriorating cash/quality must block growth spend until margin+quality proof",
    flags: { cashRisk: true, capacityRisk: true },
  })),
  mk(A("A2", {
    title: "B2B hotel towel contract — tempting volume, bad margin",
    archetype: "laundry_dry_cleaning", businessType: "Commercial laundry",
    decisionCategory: "marketing_opportunity_contract", locationKey: "kolkata",
    ownerGoal: "Win a hotel contract for revenue and credibility",
    messyFacts: [
      "Hotel offers 100 kg towels + 100 kg sheets/day; competitor quotes ₹18/kg; owner considers ₹20/kg",
      "Labour reliably handles 70 kg/day; machine max 130 kg/day only with no breakdown and no retail load",
      "Hotel wants 45-day payment terms; towel rewash rate high without water/chemical control",
    ],
    numbers: { offeredKgPerDay: 200, competitorRate: 18, consideredRate: 20, reliableKgPerDay: 70, machineMaxKgPerDay: 130, paymentTermsDays: 45 },
    hiddenRootCause: "Working-capital-heavy + capacity-constrained contract; 45-day terms starve cash; ₹20/kg likely below fully-loaded cost after labour/chemicals/water/electricity/pickup/rewash/linen-damage",
    temptingBadDecision: "Accept the contract at ₹20/kg with 45-day terms for revenue and credibility",
    correctExpertDecision: "Compute fully-loaded cost/kg; require a minimum/trial rate; negotiate weekly/15-day payment; pilot capped kg/day; add damage/rewash terms; do not displace higher-margin retail unless contribution is better",
    opsiqShouldSay: [
      "Compute fully-loaded cost/kg before quoting; ₹20/kg may be below cost",
      "Capacity is constrained — pilot a capped kg/day, do not displace retail",
      "45-day terms starve cash — negotiate weekly/15-day payment",
    ],
    opsiqShouldBlock: ["Accepting a below-margin contract", "Accepting 45-day receivables without a cash buffer"],
    proofRequired: ["Cost/kg", "Capacity schedule", "Cash conversion cycle", "Trial performance"],
    reassessmentTrigger: "After a 7-day capped pilot",
    learningRuleIfFails: "If OpsIQ accepted a contract without fully-loaded cost + capacity + payment-term check, store a margin/working-capital guardrail for B2B volume offers",
    flags: { cashRisk: true, capacityRisk: true },
  })),
  mk(A("A3", {
    title: "Premium dry cleaner — staff hides damage",
    archetype: "laundry_dry_cleaning", businessType: "Premium dry cleaner",
    decisionCategory: "staff_process_equipment", locationKey: "singapore",
    ownerGoal: "Protect premium reputation while keeping same/next-day promise",
    messyFacts: [
      "Complaints of shrinkage + chemical smell; staff logs say 'completed OK'",
      "Task photos not tied to item IDs; manager calls complaints 'picky customers'",
      "Refunds rising while revenue looks stable",
    ],
    numbers: { promise: "same/next-day", refundTrend: "rising" },
    hiddenRootCause: "Weak staff completion proof; QC after packaging not before; possible solvent/process defect",
    temptingBadDecision: "Hand out discount vouchers to angry customers and carry on",
    correctExpertDecision: "Pause same-day promise for affected categories; add pre/post item-level photo proof; QC before packaging; audit machine/chemical process; proactively contact affected customers",
    opsiqShouldSay: [
      "Staff 'completed OK' is not item-level proof — require pre/post photos tied to item IDs",
      "Move QC before packaging and audit the solvent/process",
      "Pause the same-day promise for affected categories until QC is fixed",
    ],
    opsiqShouldBlock: ["Continuing the same-day promise without a QC fix", "Accepting staff completion proof without item-level evidence"],
    proofRequired: ["QC checklist", "Machine maintenance/chemical records", "Item-level proof"],
    reassessmentTrigger: "10 days: complaint rate and refund rate",
    learningRuleIfFails: "If OpsIQ accepted staff self-reported completion as proof, store a proof-gaming caution: staff/equipment claims need independent item-level evidence",
    flags: { hostile: true, complianceRisk: false, capacityRisk: true },
  })),

  // ── Pack B — Housekeeping / cleaning / facility ──
  mk(A("B1", {
    title: "Housekeeping contractor — fake attendance + client churn",
    archetype: "housekeeping_facility", businessType: "Residential housekeeping contractor",
    decisionCategory: "staff_process_equipment", locationKey: "kolkata",
    ownerGoal: "Win 2 more complexes; pipeline looks strong",
    messyFacts: [
      "18 cleaners across 5 complexes; clients report bathrooms not cleaned, staff absent, supervisors unreachable",
      "Supervisor sheet shows 96% attendance but GPS/photo proof inconsistent; turnover 22%/month",
    ],
    numbers: { cleaners: 18, complexes: 5, reportedAttendancePct: 96, monthlyTurnoverPct: 22 },
    hiddenRootCause: "Supervisor collusion + fake attendance; poor route/workload allocation; deep-clean training gaps",
    temptingBadDecision: "Bid for 2 new complexes because the pipeline looks strong",
    correctExpertDecision: "Freeze expansion; audit attendance with random client confirmation; reset workload per cleaner; train on top complaint tasks; require geo/time-stamped before/after photos + client signoff",
    opsiqShouldSay: [
      "96% attendance conflicts with absence complaints — the proof is gamed; verify independently",
      "Freeze expansion until attendance/proof and churn stabilise",
      "Reset workload and train on the top complaint tasks",
    ],
    opsiqShouldBlock: ["New complex bids until attendance/proof and churn stabilise"],
    proofRequired: ["Random audit logs", "Complaint closure proof", "Cleaner workload map"],
    reassessmentTrigger: "21 days: complaint rate, attendance variance, retention",
    learningRuleIfFails: "If OpsIQ trusted supervisor attendance contradicted by client complaints, store a proof-gaming rule for self-reported attendance",
    flags: { hostile: true, capacityRisk: true },
  })),
  mk(A("B2", {
    title: "Office cleaning — underpriced night-shift contract",
    archetype: "housekeeping_facility", businessType: "Office cleaning service",
    decisionCategory: "marketing_opportunity_contract", locationKey: "uae",
    ownerGoal: "Enter a premium tower by matching competitor price",
    messyFacts: [
      "7-day night-shift scope; 2-hour replacement SLA on absence",
      "Owner's quote excludes supervisor cost and overtime; labour accommodation/transport rising",
    ],
    numbers: { coverageDaysPerWeek: 7, replacementSlaHours: 2 },
    hiddenRootCause: "Quote misses true labour, transport, overtime, supervision and compliance obligations",
    temptingBadDecision: "Match the competitor price to win the premium building",
    correctExpertDecision: "Requote with full cost; separate base scope vs extra work; price the absence/replacement SLA; add escalation + payment terms",
    opsiqShouldSay: [
      "The quote excludes supervisor/overtime/transport — it is below true cost",
      "Price the 2-hour replacement SLA as a staffing buffer cost",
      "Flag UAE labour/visa obligations for professional review",
    ],
    opsiqShouldBlock: ["A below-cost quote", "An SLA without a staffing buffer"],
    proofRequired: ["Costed manpower plan", "SLA risk model", "Margin calculation"],
    reassessmentTrigger: "Before quote submission",
    learningRuleIfFails: "If OpsIQ approved a quote missing supervision/overtime/SLA cost, store a contract costing guardrail",
    flags: { cashRisk: false, complianceRisk: true },
  })),
  mk(A("B3", {
    title: "Facility cleaning — chemical stock theft",
    archetype: "housekeeping_facility", businessType: "Small commercial cleaning contractor",
    decisionCategory: "staff_process_equipment", locationKey: "uk",
    ownerGoal: "Cut rising chemical cost",
    messyFacts: [
      "Chemical spend +38% but revenue flat; productivity down; complaints about diluted liquids",
      "Supervisor signs all stock-issue sheets; supplier invoices look normal",
    ],
    numbers: { chemicalSpendChangePct: 38 },
    hiddenRootCause: "Internal leakage/theft or unauthorised use; no per-site stock reconciliation",
    temptingBadDecision: "Switch supplier or buy cheaper chemicals",
    correctExpertDecision: "Site-level stock issue/reconciliation; dilution controls; supervisor-independent stock audit; complaint-to-stock correlation",
    opsiqShouldSay: [
      "Normal supplier invoices + 38% spend + dilution complaints point to internal leakage, not the supplier",
      "Run a supervisor-independent per-site stock reconciliation before any supplier change",
    ],
    opsiqShouldBlock: ["Supplier switch without a stock audit"],
    proofRequired: ["Stock variance by site", "Dilution logs", "Complaint mapping"],
    reassessmentTrigger: "2 weeks: stock variance and complaints",
    learningRuleIfFails: "If OpsIQ treated theft as a supplier-price symptom, store a root-cause rule for input-cost spikes with flat revenue",
    flags: { hostile: true },
  })),

  // ── Pack C — Food / restaurant / cloud kitchen / catering ──
  mk(A("C1", {
    title: "Cloud kitchen — sales up, platform commissions kill margin",
    archetype: "food_restaurant_cloudkitchen", businessType: "Cloud kitchen",
    decisionCategory: "cash_margin_working_capital", locationKey: "kolkata",
    ownerGoal: "Scale orders; owner believes rising order count = scaling",
    messyFacts: [
      "App sales ₹5.5L/month; commission 28%, packaging 9%, owner-funded discounts 12%, food cost 35%; fixed ₹1.65L",
      "Ratings fell 4.3 → 3.8 (late delivery, portion complaints)",
    ],
    numbers: { appSales: 550000, commissionPct: 28, packagingPct: 9, discountPct: 12, foodCostPct: 35, fixedCosts: 165000, ratingPrev: 4.3, ratingNow: 3.8 },
    hiddenRootCause: "Unit economics negative on discounted platform orders; quality decline from overload",
    temptingBadDecision: "Spend more on platform ads because order count rose",
    correctExpertDecision: "Compute contribution by SKU/channel; stop discounting loss-making SKUs; simplify menu; push direct repeat only after quality recovers; fix prep time + packaging",
    opsiqShouldSay: [
      "After 28% commission + 9% packaging + 12% discount + 35% food cost, discounted SKUs are loss-making",
      "Do not buy more ads — fix SKU margin and ratings first",
      "Simplify the menu and fix prep-time/packaging",
    ],
    opsiqShouldBlock: ["More platform ads until SKU margin and ratings recover"],
    proofRequired: ["SKU margin", "Rating trend", "Prep-time SLA"],
    reassessmentTrigger: "14 days: SKU margin and rating trend",
    learningRuleIfFails: "If OpsIQ scaled ads on gross sales ignoring commission/contribution, store a unit-economics guardrail for platform-commission businesses",
    flags: { cashRisk: true, capacityRisk: true },
  })),
  mk(A("C2", {
    title: "Restaurant — weekends full, weekdays lose money",
    archetype: "food_restaurant_cloudkitchen", businessType: "Casual restaurant",
    decisionCategory: "multi_branch_portfolio", locationKey: "australia",
    ownerGoal: "Open a second branch citing weekend demand",
    messyFacts: [
      "Weekends 95% occupancy, weekdays 25%; labour scheduled evenly; weekday food waste high",
    ],
    numbers: { weekendOccupancyPct: 95, weekdayOccupancyPct: 25 },
    hiddenRootCause: "Not a capacity problem — weekday demand/labour-scheduling/waste are the problem",
    temptingBadDecision: "Open a second branch",
    correctExpertDecision: "Optimise weekday staffing/menu; cut prep/waste; targeted weekday offers with margin limits; improve booking data — fix weekly profitability before any branch",
    opsiqShouldSay: [
      "The constraint is weekday demand + even labour scheduling + waste, not seating capacity",
      "Fix weekly profitability and the staffing model before a second branch",
    ],
    opsiqShouldBlock: ["A second branch until weekly profitability and the staffing model work"],
    proofRequired: ["Day-wise P&L", "Waste log", "Labour cost %"],
    reassessmentTrigger: "4 weeks: weekday P&L and waste",
    learningRuleIfFails: "If OpsIQ approved expansion on peak demand while weekly economics were unproven, store an expansion-readiness guardrail",
    flags: { multiBranch: true },
  })),
  mk(A("C3", {
    title: "Catering — big wedding order creates cash risk",
    archetype: "food_restaurant_cloudkitchen", businessType: "Catering service",
    decisionCategory: "cash_margin_working_capital", locationKey: "tier2_india",
    ownerGoal: "Win an ₹8L wedding order for prestige",
    messyFacts: [
      "₹8L order; client offers 20% advance, balance after event; vendor advance needs 60% upfront",
      "Owner cash ₹1.2L; a prior client paid 45 days late",
    ],
    numbers: { orderValue: 800000, clientAdvancePct: 20, vendorUpfrontPct: 60, ownerCash: 120000 },
    hiddenRootCause: "A profitable order can still bankrupt cash flow (20% in vs 60% out)",
    temptingBadDecision: "Accept on 20% advance for the prestige",
    correctExpertDecision: "Require milestone advance; lock menu + guest count; vendor payment schedule; penalty/late-payment terms; do not start procurement without cash coverage",
    opsiqShouldSay: [
      "20% advance against 60% upfront vendor cost on ₹1.2L cash will bankrupt the order — do not start procurement uncovered",
      "Require milestone advances and lock menu + guest count",
    ],
    opsiqShouldBlock: ["Accepting 20% advance against 60% upfront cost"],
    proofRequired: ["Cash-flow schedule", "Signed terms", "Vendor quotes"],
    reassessmentTrigger: "Before acceptance",
    learningRuleIfFails: "If OpsIQ accepted a cash-negative order on prestige, store a working-capital-trap rule for large orders with back-loaded payment",
    flags: { cashRisk: true, ownerEmotional: true },
  })),

  // ── Pack D — Retail / pharmacy / grocery / apparel ──
  mk(A("D1", {
    title: "Grocery — high sales, stockouts, dead inventory",
    archetype: "retail_pharmacy_grocery_apparel", businessType: "Grocery/convenience retail",
    decisionCategory: "cash_margin_working_capital", locationKey: "tier2_india",
    ownerGoal: "Buy more inventory to capture sales",
    messyFacts: [
      "Sales ₹12L/month but no cash for supplier payments; fast SKUs out of stock, slow premium items piled up",
      "Staff buys on supplier schemes; credit customers delay payment",
    ],
    numbers: { monthlySales: 1200000 },
    hiddenRootCause: "Working capital trapped in dead stock + receivables",
    temptingBadDecision: "Take a loan to buy more inventory",
    correctExpertDecision: "SKU ABC analysis; stop slow-stock purchasing; liquidate dead stock; tighten customer credit; reorder only fast-moving/high-margin SKUs",
    opsiqShouldSay: [
      "Cash is trapped in dead stock and receivables — a loan worsens it",
      "Liquidate dead stock, tighten credit, reorder only fast-moving high-margin SKUs",
    ],
    opsiqShouldBlock: ["A loan for inventory without SKU cleanup"],
    proofRequired: ["Ageing inventory", "SKU margin/velocity", "Receivables ageing"],
    reassessmentTrigger: "Weekly stock/cash review",
    learningRuleIfFails: "If OpsIQ recommended an inventory loan over working-capital cleanup, store a working-capital-trap rule",
    flags: { cashRisk: true },
  })),
  mk(A("D2", {
    title: "Pharmacy — compliance + expiry risk",
    archetype: "retail_pharmacy_grocery_apparel", businessType: "Pharmacy",
    decisionCategory: "compliance_location_review", locationKey: "kolkata",
    ownerGoal: "Recover slow stock via aggressive refill marketing",
    messyFacts: [
      "Expired/near-expiry medicines found; staff substitutes when prescribed item unavailable",
      "Owner wants aggressive WhatsApp marketing for refills; inventory software not updated daily",
    ],
    numbers: {},
    hiddenRootCause: "Compliance + inventory-control failure",
    temptingBadDecision: "Push sales/marketing to clear slow (incl. near-expiry) stock",
    correctExpertDecision: "Remove expired stock; professional compliance review; ban substitution without pharmacist/legal compliance; daily inventory update",
    opsiqShouldSay: [
      "Do not market near-expiry/expired stock; remove it and reconcile inventory daily",
      "Substitution and refill marketing need a pharmacist/professional compliance review — I cannot give definitive legal/medical advice",
    ],
    opsiqShouldBlock: ["Marketing expired/near-expiry stock", "Giving definitive medical/legal advice"],
    proofRequired: ["Expiry audit", "Pharmacist verification", "Inventory reconciliation"],
    reassessmentTrigger: "Immediate and weekly",
    learningRuleIfFails: "If OpsIQ enabled near-expiry marketing or gave definitive legal/medical advice, store a compliance boundary rule (flag professional review)",
    flags: { complianceRisk: true },
  })),
  mk(A("D3", {
    title: "Apparel boutique — discounts train customers to wait",
    archetype: "retail_pharmacy_grocery_apparel", businessType: "Small apparel boutique",
    decisionCategory: "marketing_opportunity_contract", locationKey: "uk",
    ownerGoal: "Clear stock and lift revenue",
    messyFacts: [
      "Footfall stable but revenue down; gross margin 58% → 38%; frequent 'clearance' promos; customers ask when the next sale is",
      "Buying based on owner taste, not sell-through",
    ],
    numbers: { marginPrevPct: 58, marginNowPct: 38 },
    hiddenRootCause: "Discount addiction + poor buying discipline",
    temptingBadDecision: "Increase discounts to clear stock",
    correctExpertDecision: "Stop blanket discounts; segment inventory; bundle slow stock; limited premium drops; track sell-through by category",
    opsiqShouldSay: [
      "Frequent clearances have trained customers to wait — more discounts deepen the margin collapse",
      "Stop blanket discounting; bundle slow stock and track sell-through by category",
    ],
    opsiqShouldBlock: ["More blanket discounting"],
    proofRequired: ["Margin trend", "Sell-through report", "Promotion history"],
    reassessmentTrigger: "30 days: margin and sell-through",
    learningRuleIfFails: "If OpsIQ recommended more discounting into a margin collapse, store a discount-addiction guardrail",
    flags: {},
  })),

  // ── Pack E — Professional services / agencies ──
  mk(A("E1", {
    title: "Marketing agency — growth but founder overloaded",
    archetype: "professional_services_agency", businessType: "Marketing/PR agency",
    decisionCategory: "staff_process_equipment", locationKey: "kolkata",
    ownerGoal: "Hire 3 creatives to handle growth",
    messyFacts: [
      "Revenue ₹2L → ₹5L/month; founder works 14h/day; clients complain about delayed creatives",
      "4 juniors, no account manager; scope creep + unpaid revisions",
    ],
    numbers: { revenuePrev: 200000, revenueNow: 500000, founderHours: 14 },
    hiddenRootCause: "Account/process bottleneck (not creative headcount); scope creep + weak intake",
    temptingBadDecision: "Hire 3 more creatives",
    correctExpertDecision: "Define packages/scope; add a project/account manager first; stop unpaid custom revisions; introduce an approval workflow",
    opsiqShouldSay: [
      "The bottleneck is account management + scope, not creative capacity — hiring creatives won't fix delays",
      "Add an account/PM role, define scope/packages, and stop unpaid revisions",
    ],
    opsiqShouldBlock: ["Hiring creatives before the process/account bottleneck is fixed"],
    proofRequired: ["Task ageing", "Revision count", "Founder time log"],
    reassessmentTrigger: "2 weeks: task ageing and founder hours",
    learningRuleIfFails: "If OpsIQ added headcount to a process bottleneck, store a bottleneck-diagnosis rule (symptom vs root cause)",
    flags: { ownerEmotional: true },
  })),
  mk(A("E2", {
    title: "Software agency — fixed-price project underpriced",
    archetype: "professional_services_agency", businessType: "Software agency",
    decisionCategory: "marketing_opportunity_contract", locationKey: "us",
    ownerGoal: "Accept a fixed-price app for portfolio credibility",
    messyFacts: [
      "$18,000 fixed price, vague scope; 30% upfront / 70% after launch; team estimates 4 months × 3 devs",
    ],
    numbers: { fixedPrice: 18000, upfrontPct: 30, months: 4, developers: 3 },
    hiddenRootCause: "Scope + payment risk; likely negative margin",
    temptingBadDecision: "Accept the fixed-price vague-scope project for credibility",
    correctExpertDecision: "Break into a paid discovery; milestone billing; change-request terms; margin + capacity calculation",
    opsiqShouldSay: [
      "4 months × 3 devs against $18k fixed with vague scope and back-loaded payment is likely loss-making",
      "Start with paid discovery and milestone billing with change-request terms",
    ],
    opsiqShouldBlock: ["A fixed-price, vague-scope contract with back-loaded payment"],
    proofRequired: ["SOW", "Effort estimate", "Payment schedule"],
    reassessmentTrigger: "Before signing",
    learningRuleIfFails: "If OpsIQ accepted a vague fixed-price project, store a scope/payment-risk contract guardrail",
    flags: { cashRisk: true, remoteOwner: true },
  })),
  mk(A("E3", {
    title: "Accounting firm — deadline-season capacity overload",
    archetype: "professional_services_agency", businessType: "Bookkeeping/accounting firm",
    decisionCategory: "compliance_location_review", locationKey: "singapore",
    ownerGoal: "Take 15 new referred clients now",
    messyFacts: [
      "Tax/GST deadline approaching; 2 seniors overloaded; junior errors rising; owner wants 15 new clients",
    ],
    numbers: { newClients: 15, overloadedSeniors: 2 },
    hiddenRootCause: "Deadline + quality risk from capacity overload",
    temptingBadDecision: "Accept all 15 referrals immediately",
    correctExpertDecision: "Defer low-fit clients; intake cutoff; temporary reviewer; prioritise existing compliance deadlines",
    opsiqShouldSay: [
      "Taking 15 clients into an overloaded deadline season risks existing clients' compliance and quality",
      "Set an intake cutoff, add a reviewer, prioritise current deadlines",
    ],
    opsiqShouldBlock: ["Taking new clients without capacity/review control"],
    proofRequired: ["Deadline calendar", "Staff workload", "Error rate"],
    reassessmentTrigger: "Weekly during deadline season",
    learningRuleIfFails: "If OpsIQ accepted intake that endangers existing compliance deadlines, store a capacity/compliance guardrail",
    flags: { capacityRisk: true, complianceRisk: true },
  })),

  // ── Pack F — Health / care / fitness ──
  mk(A("F1", {
    title: "Clinic — appointment growth but wait-time complaints",
    archetype: "health_care_fitness", businessType: "Small clinic",
    decisionCategory: "marketing_opportunity_contract", locationKey: "tier2_india",
    ownerGoal: "Run more ads to grow appointments",
    messyFacts: [
      "Appointments +40%; patient wait 75 min; Google reviews falling; receptionist overbooks; follow-ups missed",
    ],
    numbers: { appointmentsChangePct: 40, waitMinutes: 75 },
    hiddenRootCause: "Scheduling/process bottleneck",
    temptingBadDecision: "More ads",
    correctExpertDecision: "Pause ads; fix appointment slots; triage urgent/non-urgent; add a follow-up system",
    opsiqShouldSay: [
      "75-minute waits and falling reviews mean ads will worsen experience — fix scheduling first",
      "Add slot control, triage, and a follow-up system",
    ],
    opsiqShouldBlock: ["Ads while patient experience is failing"],
    proofRequired: ["Wait-time log", "Review trend", "No-show/follow-up log"],
    reassessmentTrigger: "2 weeks: wait time and reviews",
    learningRuleIfFails: "If OpsIQ recommended marketing while service quality was broken, store a marketing-while-broken guardrail",
    flags: { capacityRisk: true },
  })),
  mk(A("F2", {
    title: "Home elderly care — caregiver absenteeism risk",
    archetype: "health_care_fitness", businessType: "Home elderly care",
    decisionCategory: "staff_process_equipment", locationKey: "kolkata",
    ownerGoal: "Add clients to meet high demand",
    messyFacts: [
      "12 caregivers; families report lateness; some work 12h shifts without rest; weak replacement pool",
    ],
    numbers: { caregivers: 12, shiftHours: 12 },
    hiddenRootCause: "Staffing reliability + ethical workload risk",
    temptingBadDecision: "Add clients due to high demand",
    correctExpertDecision: "Build a backup caregiver pool; cap workload; proof of visit; family communication SOP",
    opsiqShouldSay: [
      "12-hour shifts without rest are unsafe/unfair and unreliable — do not add clients without a backup pool",
      "Cap workload and add proof-of-visit + family communication SOP",
    ],
    opsiqShouldBlock: ["Taking new clients without backup staffing"],
    proofRequired: ["Attendance logs", "Shift hours", "Backup roster"],
    reassessmentTrigger: "21 days: attendance and shift hours",
    learningRuleIfFails: "If OpsIQ enabled growth ignoring staff overload/ethics, store a staff-overload guardrail",
    flags: { capacityRisk: true },
  })),
  mk(A("F3", {
    title: "Fitness studio — membership sales hide retention problem",
    archetype: "health_care_fitness", businessType: "Fitness studio",
    decisionCategory: "marketing_opportunity_contract", locationKey: "uae",
    ownerGoal: "Increase ad spend on the back of an influencer campaign",
    messyFacts: [
      "New memberships high (influencer); attendance drops after 3 weeks; classes crowded; trainers overloaded",
    ],
    numbers: { dropoffWeeks: 3 },
    hiddenRootCause: "Retention + capacity issue",
    temptingBadDecision: "More acquisition marketing",
    correctExpertDecision: "Improve onboarding/retention; cap class size; trainer schedule; track active usage",
    opsiqShouldSay: [
      "Sales are masking churn and over-capacity classes — more acquisition makes it worse",
      "Fix onboarding/retention and cap class size before spending",
    ],
    opsiqShouldBlock: ["Marketing push beyond class capacity"],
    proofRequired: ["Attendance cohort", "Class capacity", "Churn rate"],
    reassessmentTrigger: "30 days: cohort retention",
    learningRuleIfFails: "If OpsIQ scaled acquisition over a retention/capacity problem, store a retention-before-acquisition guardrail",
    flags: { capacityRisk: true },
  })),

  // ── Pack G — Trades / repair / small manufacturing ──
  mk(A("G1", {
    title: "HVAC contractor — high demand, poor cash",
    archetype: "trades_repair_manufacturing", businessType: "HVAC service",
    decisionCategory: "cash_margin_working_capital", locationKey: "us",
    ownerGoal: "Buy another van to handle summer demand",
    messyFacts: [
      "Summer demand high; invoices paid late; techs lack parts and revisit jobs; cash low",
    ],
    numbers: {},
    hiddenRootCause: "Receivables + first-time-fix failure (not van capacity)",
    temptingBadDecision: "Buy a van to handle demand",
    correctExpertDecision: "Improve collections; stock critical parts; track first-time-fix; rent/lease only if cash + utilization justify",
    opsiqShouldSay: [
      "The constraint is collections + first-time-fix (revisits), not van count",
      "Fix AR and parts stocking before buying a van",
    ],
    opsiqShouldBlock: ["A van purchase before cash/parts/process are fixed"],
    proofRequired: ["AR ageing", "Revisit rate", "Parts stockouts"],
    reassessmentTrigger: "2 weeks: AR and revisit rate",
    learningRuleIfFails: "If OpsIQ approved capex while AR/first-time-fix were broken, store a cash-before-capex rule",
    flags: { cashRisk: true },
  })),
  mk(A("G2", {
    title: "Printing shop — machine bottleneck + rush orders",
    archetype: "trades_repair_manufacturing", businessType: "Printing shop",
    decisionCategory: "staff_process_equipment", locationKey: "australia",
    ownerGoal: "Run a campaign for more rush orders",
    messyFacts: [
      "Rush orders profitable but disrupt standard orders; main printer downtime rising; overtime high",
    ],
    numbers: {},
    hiddenRootCause: "Equipment bottleneck + scheduling",
    temptingBadDecision: "Sell more rush jobs",
    correctExpertDecision: "Price rush at a proper premium; maintenance window; capacity calendar; limit rush slots",
    opsiqShouldSay: [
      "Rising printer downtime means more rush orders will blow lateness and overtime — fix uptime first",
      "Add a maintenance window, a capacity calendar and limited rush slots",
    ],
    opsiqShouldBlock: ["A rush campaign without machine-uptime proof"],
    proofRequired: ["Downtime log", "Order lateness", "Overtime cost"],
    reassessmentTrigger: "30 days: downtime and lateness",
    learningRuleIfFails: "If OpsIQ drove demand into an equipment bottleneck, store a capacity/equipment guardrail",
    flags: { capacityRisk: true },
  })),
  mk(A("G3", {
    title: "Small manufacturing — big retailer order",
    archetype: "trades_repair_manufacturing", businessType: "Small manufacturing unit",
    decisionCategory: "marketing_opportunity_contract", locationKey: "tier2_india",
    ownerGoal: "Win a big retailer logo with a large order",
    messyFacts: [
      "Large order, low margin; 60-day payment after delivery; raw-material prices volatile; tight working capital; quality rejects chargeable",
    ],
    numbers: { paymentTermsDays: 60 },
    hiddenRootCause: "Scale order can damage cash + margin",
    temptingBadDecision: "Accept the full order for the retailer logo",
    correctExpertDecision: "Negotiate advance/terms; raw-material price clause; quality tolerance; pilot batch",
    opsiqShouldSay: [
      "Low margin + 60-day terms + volatile inputs + chargebacks on tight capital is a cash trap",
      "Pilot a batch, negotiate advance/price-clause/quality terms before the full order",
    ],
    opsiqShouldBlock: ["The full order without working capital and terms"],
    proofRequired: ["Cost sheet", "Cash-flow model", "Contract terms"],
    reassessmentTrigger: "Before signing",
    learningRuleIfFails: "If OpsIQ accepted a low-margin back-loaded scale order, store a working-capital + margin contract guardrail",
    flags: { cashRisk: true, ownerEmotional: true },
  })),

  // ── Pack H — Education / training ──
  mk(A("H1", {
    title: "Coaching center — high enrollment, poor results",
    archetype: "education_training", businessType: "Coaching center",
    decisionCategory: "marketing_opportunity_contract", locationKey: "tier2_india",
    ownerGoal: "More admissions marketing",
    messyFacts: [
      "Enrollment up but student results poor; parent complaints rising; teachers overloaded; irregular attendance",
    ],
    numbers: {},
    hiddenRootCause: "Academic-delivery failure + teacher load",
    temptingBadDecision: "More admissions",
    correctExpertDecision: "Pause aggressive enrollment; cap batch capacity; teacher support; attendance/result tracking",
    opsiqShouldSay: [
      "Poor results + overloaded teachers mean more admissions worsen outcomes and reputation",
      "Cap batch size and fix delivery before marketing",
    ],
    opsiqShouldBlock: ["Marketing without result improvement"],
    proofRequired: ["Student progress data", "Teacher workload", "Attendance"],
    reassessmentTrigger: "Monthly: results and workload",
    learningRuleIfFails: "If OpsIQ grew admissions over a delivery failure, store a deliver-before-grow guardrail",
    flags: { capacityRisk: true },
  })),
  mk(A("H2", {
    title: "Online course — launch spike, refunds later",
    archetype: "education_training", businessType: "Online course business",
    decisionCategory: "marketing_opportunity_contract", locationKey: "global_online",
    ownerGoal: "Launch the next course quickly",
    messyFacts: [
      "Launch made $30k; refunds rising; completion 18%; support tickets high",
    ],
    numbers: { launchRevenue: 30000, completionPct: 18 },
    hiddenRootCause: "Product-delivery + expectation mismatch",
    temptingBadDecision: "Launch the next course quickly",
    correctExpertDecision: "Fix onboarding/content/support; improve completion; survey refund reasons; delay next launch",
    opsiqShouldSay: [
      "18% completion + rising refunds is a delivery problem — a new launch compounds refunds",
      "Fix onboarding/support and survey refund reasons before the next launch",
    ],
    opsiqShouldBlock: ["A new launch before the refund/completion issue is fixed"],
    proofRequired: ["Refund reasons", "Completion cohort", "Support ticket categories"],
    reassessmentTrigger: "30 days: completion and refunds",
    learningRuleIfFails: "If OpsIQ launched again over a delivery/refund problem, store a fix-delivery-before-relaunch guardrail",
    flags: { remoteOwner: true },
  })),

  // ── Pack I — Logistics / delivery / fleet ──
  mk(A("I1", {
    title: "Local delivery — fuel + failed-delivery losses",
    archetype: "logistics_delivery_fleet", businessType: "Local courier/delivery",
    decisionCategory: "staff_process_equipment", locationKey: "kolkata",
    ownerGoal: "Hire more riders for rising orders",
    messyFacts: [
      "Orders up; fuel cost up; failed deliveries 18%; riders paid per delivery (rushed attempts); no call-before-delivery",
    ],
    numbers: { failedDeliveryPct: 18 },
    hiddenRootCause: "Incentive + routing issue (not headcount)",
    temptingBadDecision: "Hire more riders",
    correctExpertDecision: "Route planning; call-before-delivery SOP; incentive tied to successful delivery; failed-delivery tracking",
    opsiqShouldSay: [
      "18% failed deliveries with pay-per-attempt is an incentive/routing problem — more riders multiply failures",
      "Tie incentives to successful delivery and add a call-before-delivery SOP",
    ],
    opsiqShouldBlock: ["Hiring before the route/failed-delivery fix"],
    proofRequired: ["Failed-delivery log", "Rider route data", "Fuel per order"],
    reassessmentTrigger: "14 days: failed-delivery rate",
    learningRuleIfFails: "If OpsIQ added headcount to an incentive/process failure, store a fix-incentive-before-headcount rule",
    flags: { capacityRisk: true },
  })),
  mk(A("I2", {
    title: "Fleet operator — maintenance ignored",
    archetype: "logistics_delivery_fleet", businessType: "Small fleet operator",
    decisionCategory: "staff_process_equipment", locationKey: "uae",
    ownerGoal: "Add two vehicles to meet bookings",
    messyFacts: [
      "Vehicles fully booked; breakdowns rising; drivers skip inspection checklist; owner wants 2 more vehicles",
    ],
    numbers: { plannedNewVehicles: 2 },
    hiddenRootCause: "Maintenance-control failure",
    temptingBadDecision: "Expand the fleet",
    correctExpertDecision: "Enforce inspection proof; preventive maintenance schedule; downtime-cost tracking; add a vehicle only after uptime is stable",
    opsiqShouldSay: [
      "Rising breakdowns + skipped inspections mean more vehicles add more downtime, not capacity",
      "Enforce inspection proof and preventive maintenance before expanding",
    ],
    opsiqShouldBlock: ["Expansion while maintenance is non-compliant"],
    proofRequired: ["Inspection logs", "Breakdown history", "Maintenance schedule"],
    reassessmentTrigger: "30 days: uptime and breakdowns",
    learningRuleIfFails: "If OpsIQ expanded a fleet with broken maintenance proof, store an uptime-before-expansion guardrail",
    flags: { capacityRisk: true },
  })),

  // ── Pack J — Digital / e-commerce / D2C / SaaS ──
  mk(A("J1", {
    title: "D2C brand — ROAS looks good but returns kill profit",
    archetype: "digital_ecommerce_d2c_saas", businessType: "D2C apparel/accessory brand",
    decisionCategory: "cash_margin_working_capital", locationKey: "tier2_india",
    ownerGoal: "Double ad budget on a 3.2 ROAS",
    messyFacts: [
      "Ads show ROAS 3.2; return rate 28%; COD RTO high; packaging/shipping high; owner wants to double ads",
    ],
    numbers: { roas: 3.2, returnPct: 28 },
    hiddenRootCause: "Net contribution after returns/RTO is weak",
    temptingBadDecision: "Scale ads on gross ROAS",
    correctExpertDecision: "Compute contribution after returns; reduce COD/RTO; fix product-page sizing/expectations; segment profitable SKUs",
    opsiqShouldSay: [
      "Gross ROAS 3.2 with 28% returns + high RTO can be net-loss — compute contribution after returns first",
      "Reduce COD/RTO and scale only profitable SKUs",
    ],
    opsiqShouldBlock: ["Scaling ads on gross ROAS only"],
    proofRequired: ["Net margin by channel/SKU", "Return/RTO reasons"],
    reassessmentTrigger: "2 weeks: net contribution",
    learningRuleIfFails: "If OpsIQ scaled on gross ROAS ignoring returns, store a net-contribution guardrail for D2C",
    flags: { cashRisk: true },
  })),
  mk(A("J2", {
    title: "Micro-SaaS — free users overload support",
    archetype: "digital_ecommerce_d2c_saas", businessType: "Micro-SaaS",
    decisionCategory: "marketing_opportunity_contract", locationKey: "global_online",
    ownerGoal: "Grow the free user base",
    messyFacts: [
      "8,000 free users, 140 paying; support overloaded; paid churn high; founder wants more free acquisition",
    ],
    numbers: { freeUsers: 8000, payingUsers: 140 },
    hiddenRootCause: "Poor conversion + support economics",
    temptingBadDecision: "Grow the free user base",
    correctExpertDecision: "Limit free support; improve onboarding; identify the paid ICP; fix churn before acquisition",
    opsiqShouldSay: [
      "8,000 free / 140 paid with overloaded support means more free users worsen unit economics",
      "Fix paid churn + support economics before acquiring more free users",
    ],
    opsiqShouldBlock: ["A free-acquisition push while paid churn/support are poor"],
    proofRequired: ["Conversion cohort", "Churn reasons", "Support tickets per segment"],
    reassessmentTrigger: "30 days: conversion and churn",
    learningRuleIfFails: "If OpsIQ grew free users over broken conversion/support, store a fix-economics-before-acquisition rule",
    flags: { remoteOwner: true },
  })),

  // ── Pack K — Agri / rural ──
  mk(A("K1", {
    title: "Dairy — milk yield falling, feed cost rising",
    archetype: "agri_rural", businessType: "Small dairy",
    decisionCategory: "cash_margin_working_capital", locationKey: "rural_india",
    ownerGoal: "Loan to buy more cows",
    messyFacts: [
      "Yield down 18%; feed cost up; some cows sick; buyer delays payment; owner wants a loan for more cows",
    ],
    numbers: { yieldChangePct: -18 },
    hiddenRootCause: "Animal-health/feed/cash issue",
    temptingBadDecision: "Buy more cows",
    correctExpertDecision: "Veterinary check; feed optimisation; payment collection; improve yield before expansion",
    opsiqShouldSay: [
      "Falling yield + sick cows + delayed payment means more cows multiply losses",
      "Fix herd health/feed and collect payment before any expansion loan",
    ],
    opsiqShouldBlock: ["An expansion loan before herd health/cash are fixed"],
    proofRequired: ["Vet report", "Yield per animal", "Feed cost per litre", "Receivables"],
    reassessmentTrigger: "30 days: yield per animal and cash",
    learningRuleIfFails: "If OpsIQ funded expansion over a herd-health/cash problem, store a fix-core-before-expansion rule",
    flags: { cashRisk: true },
  })),
  mk(A("K2", {
    title: "Poultry — mortality rising",
    archetype: "agri_rural", businessType: "Poultry farm",
    decisionCategory: "compliance_location_review", locationKey: "tier2_india",
    ownerGoal: "Increase batch size before festival demand",
    messyFacts: [
      "Mortality 3% → 9%; feed supplier changed; heat stress; owner wants a bigger batch before the festival",
    ],
    numbers: { mortalityPrevPct: 3, mortalityNowPct: 9 },
    hiddenRootCause: "Biosecurity/feed/environment issue",
    temptingBadDecision: "Increase batch size",
    correctExpertDecision: "Veterinary/biosecurity review; feed audit; temperature control; do not increase batch until mortality normalises",
    opsiqShouldSay: [
      "Tripled mortality after a feed change + heat stress means scaling the flock multiplies death loss",
      "Run a biosecurity/feed review and fix temperature before any batch increase",
    ],
    opsiqShouldBlock: ["Scaling the flock with high mortality"],
    proofRequired: ["Mortality log", "Vet/biosecurity check", "Feed batch records"],
    reassessmentTrigger: "2 weeks: mortality rate",
    learningRuleIfFails: "If OpsIQ scaled a flock with high mortality, store a biosecurity-before-scale guardrail",
    flags: { capacityRisk: true, complianceRisk: true },
  })),

  // ── Pack L — Multi-location / franchise / portfolio ──
  mk(A("L1", {
    title: "Multi-location owner — one branch subsidizes another",
    archetype: "multi_location_franchise_portfolio", businessType: "Two-branch service business",
    decisionCategory: "multi_branch_portfolio", locationKey: "kolkata",
    ownerGoal: "Open a third branch citing total revenue growth",
    messyFacts: [
      "Kolkata branch profitable; Siliguri growing revenue but cash-negative; shared staff + owner stretched; owner wants a third branch",
    ],
    numbers: {},
    hiddenRootCause: "Branch-level profitability unclear; weak branch controls; cross-subsidy",
    temptingBadDecision: "Open a third branch because total revenue grew",
    correctExpertDecision: "Branch-level P&L; stop cross-subsidy; fix Siliguri unit economics; no third branch until both branches are stable",
    opsiqShouldSay: [
      "Total revenue hides that Siliguri is cash-negative and subsidised — fix branch unit economics first",
      "No third branch until both branches are independently stable",
    ],
    opsiqShouldBlock: ["A third branch while a current branch is cash-negative and subsidised"],
    proofRequired: ["Branch P&L", "Cash by branch", "Owner attention load"],
    reassessmentTrigger: "Monthly: branch-level P&L",
    learningRuleIfFails: "If OpsIQ approved a third branch on aggregate revenue with a loss-making branch, store a branch-economics-before-expansion rule",
    flags: { multiBranch: true, cashRisk: true, remoteOwner: true },
  })),
  mk(A("L2", {
    title: "Franchise store — brand rules conflict with local economics",
    archetype: "multi_location_franchise_portfolio", businessType: "Franchise retail/service",
    decisionCategory: "marketing_opportunity_contract", locationKey: "singapore",
    ownerGoal: "Increase local ads to fix weak conversion",
    messyFacts: [
      "Brand fixes pricing/promotion; mall rent high; premium-service expectation; franchise marketing brings footfall but conversion low; owner cannot change core pricing",
    ],
    numbers: {},
    hiddenRootCause: "Local economics vs brand constraints mismatch",
    temptingBadDecision: "Increase local ads",
    correctExpertDecision: "Improve conversion/service mix; upsell approved premium add-ons; negotiate mall/brand support; track unit economics per service",
    opsiqShouldSay: [
      "Footfall is fine but conversion is the gap — more ads won't fix conversion or fixed-price margin",
      "Improve service-mix conversion and approved upsells; negotiate brand/mall support",
    ],
    opsiqShouldBlock: ["More local ads without a conversion/margin fix"],
    proofRequired: ["Footfall conversion", "Service-mix margin", "Brand constraint list"],
    reassessmentTrigger: "30 days: conversion and service-mix margin",
    learningRuleIfFails: "If OpsIQ recommended ads over a conversion/constraint problem, store a conversion-before-acquisition guardrail",
    flags: {},
  })),
];

export const SEED_CASE_IDS = SEED_CASES.map((c) => c.id);
