/**
 * SEQUENTIAL BUSINESS SIMULATIONS source register — privacy-clean composite/sector sources for Pack 10. Validated
 * by the existing `sourceRecordSchema` (no PII). Composite sourcing (not fabrication). Every counted simulation is
 * source-backed via one of these ids. Sources anchor the multi-event narratives (a week, a slow leak, a scaling
 * push, a gaming attempt, a cash crisis, a customer/vendor shock, an owner-away stretch, a compound crisis).
 */
import { sourceRecordSchema, type SourceRecord } from "../../behavioral-validation/public-cases/source-register";

const ACCESSED = "2026-07-02";
const s = (r: SourceRecord): SourceRecord => sourceRecordSchema.parse(r);

export const BUSINESS_SIMULATION_SOURCES: SourceRecord[] = [
  s({ id: "SRC-SIM-NORMALWEEK", type: "case_study", title: "A normal operating week", citation: "controls case — routine week", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "high", factsUsed: ["a normal week is mostly routine actions with a few owner calls", "the supervisor should not over-escalate"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-SIM-LEAKAGE", type: "finance_example", title: "Slow leakage over weeks", citation: "finance example — gradual drift", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["a slow margin/complaint/cash drift builds unnoticed", "confirm the trend before acting; escalate when proven"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-SIM-GROWTH", type: "sector_example", title: "A scaling / growth push", citation: "sector example — growth sequence", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["scaling decisions are material owner calls", "prove ROI/capacity/cash before committing"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-SIM-GAMING", type: "failure_postmortem", title: "Staff / proof gaming across a week", citation: "fraud post-mortem — proof gaming", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["gaming attempts must be blocked, not rewarded", "escalate confirmed manipulation to the owner"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-SIM-CASHCRISIS", type: "failure_postmortem", title: "A cash crisis unfolding", citation: "failure post-mortem — cash crisis sequence", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["a cash crisis deteriorates event by event", "protect cash; owner-gate; insolvency is a legal line"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-SIM-CUSTOMERVENDOR", type: "case_study", title: "A customer / vendor issue evolving", citation: "controls case — customer/vendor sequence", accessedDate: ACCESSED, geography: "global", businessCategory: "b2b-contractor", reliability: "high", completeness: "medium", factsUsed: ["a key account/vendor issue evolves over days", "material relationship/contract calls are owner-gated"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-SIM-OWNERAWAY", type: "staffing_ops", title: "Owner unavailable stretch", citation: "operations summary — owner-away period", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["when the owner is away, owner-gated decisions must HOLD, not auto-proceed", "routine work continues; material calls wait or escalate"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-SIM-EXTREME", type: "failure_postmortem", title: "A compound extreme crisis", citation: "failure post-mortem — compound crisis", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["fraud + safety + legal can compound in one crisis", "block unsafe moves; owner + professionals lead the response"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-SIM-ROUTINE", type: "case_study", title: "Routine in-policy action within a sequence", citation: "controls case — routine step", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "high", factsUsed: ["a routine reversible SOP-approved step proceeds with proof"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-SIM-MISSINGDATA", type: "gov_sme_guidance", title: "Missing data mid-sequence", citation: "SME guidance — decide on facts", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["a decision missing its figures needs the data first", "acting on missing data compounds the error"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-SIM-OWNERGATE", type: "case_study", title: "Owner-gated decision in a sequence", citation: "controls case — owner decision point", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["a material decision is prepared for the owner, not auto-committed"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-SIM-BOUNDARY", type: "regulatory_summary", title: "A professional/legal boundary in a sequence", citation: "regulatory summary — boundary event", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["a legal/compliance boundary event blocks and routes to a professional"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-SIM-REASSESS", type: "gov_sme_guidance", title: "Governed reassessment loop", citation: "SME guidance — reassessment cadence", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["each significant change routes into a governed re-evaluation", "reassess condition/mode/priority as facts arrive"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-SIM-MARGINDRIFT", type: "finance_example", title: "Margin drift within a sequence", citation: "finance example — margin drift beat", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "high", completeness: "medium", factsUsed: ["margin erosion surfaces gradually", "a material pricing response is an owner call"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-SIM-COMPLAINTRISE", type: "review_complaint_pattern", title: "Complaint rise within a sequence", citation: "complaint-pattern — rising complaints beat", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "medium", completeness: "medium", factsUsed: ["a rising complaint trend needs an owner response", "a boundary-crossing complaint blocks"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-SIM-CAPACITY", type: "staffing_ops", title: "Capacity strain within a sequence", citation: "operations summary — capacity beat", accessedDate: ACCESSED, geography: "global", businessCategory: "trades-repair-manufacturing", reliability: "high", completeness: "medium", factsUsed: ["capacity strain is a material owner call", "relieve the bottleneck before adding load"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-SIM-PAYROLL", type: "gov_sme_guidance", title: "Payroll pressure beat", citation: "SME guidance — payroll obligation", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["payroll pressure is owner-visible and owner-gated", "never hidden"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-SIM-FRAUDBEAT", type: "failure_postmortem", title: "Fraud/gaming beat", citation: "fraud post-mortem — manipulation beat", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["a manipulation/gaming beat must be blocked", "escalate to the owner with evidence preserved"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-SIM-SAFETYBEAT", type: "regulatory_summary", title: "Safety beat", citation: "regulatory summary — safety event", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["a safety event has mandatory handling", "block self-clearance; involve professionals"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-SIM-RECOVERY", type: "turnaround_story", title: "Recovery path after a shock", citation: "turnaround story — recovery route", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "medium", completeness: "medium", factsUsed: ["a governed re-evaluation defines the recovery route", "stabilise, then rebuild with proof"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-SIM-VENDORBEAT", type: "sector_example", title: "Vendor issue beat", citation: "sector example — vendor event", accessedDate: ACCESSED, geography: "global", businessCategory: "supply-logistics", reliability: "medium", completeness: "medium", factsUsed: ["a vendor reliability/price beat is a material owner call", "a falsified vendor proof blocks"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-SIM-CONTINUITY", type: "cyber_continuity", title: "Continuity beat", citation: "continuity summary — continuity event", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["a continuity event needs safety-first handling", "restart scope is a material owner call"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-SIM-ESCALATION", type: "staffing_ops", title: "Escalation-while-owner-away beat", citation: "operations summary — escalation beat", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["an owner-gated decision while the owner is away must HOLD/escalate", "it must not auto-proceed"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-SIM-STABILISE", type: "turnaround_story", title: "Stabilisation beat", citation: "turnaround story — stabilisation", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "medium", completeness: "medium", factsUsed: ["after a shock, stabilise the essentials first", "routine containment proceeds; material calls wait for the owner"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
];

export const BUSINESS_SIMULATION_SOURCE_BY_ID: Record<string, SourceRecord> = Object.fromEntries(
  BUSINESS_SIMULATION_SOURCES.map((r) => [r.id, r]),
);
