/**
 * CUSTOMER / VENDOR / MARKET source register — privacy-clean composite/sector sources for Pack 7. Validated by the
 * existing `sourceRecordSchema` (no PII). Composite sourcing (not fabrication). Every counted scenario is
 * source-backed via one of these ids. The through-line: routine in-policy customer/vendor handling proceeds with
 * proof; missing figures block on data; material relationship/contract/pricing calls are owner-gated; and a
 * consumer/contract/anti-competitive boundary — or a fraudulent refund or falsified vendor credential — is blocked.
 */
import { sourceRecordSchema, type SourceRecord } from "../../behavioral-validation/public-cases/source-register";

const ACCESSED = "2026-07-02";
const s = (r: SourceRecord): SourceRecord => sourceRecordSchema.parse(r);

export const CUSTOMER_VENDOR_MARKET_SOURCES: SourceRecord[] = [
  s({ id: "SRC-CVM-COMPLAINT", type: "review_complaint_pattern", title: "Customer complaint resolution", citation: "complaint-pattern summary — resolution handling", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "medium", completeness: "medium", factsUsed: ["routine in-policy complaints are handled with proof", "a systemic or escalating complaint is an owner call"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-CVM-REFUND", type: "finance_example", title: "Customer refund / dispute", citation: "finance example — refund dispute", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "medium", completeness: "medium", factsUsed: ["in-policy refunds are routine", "a material or contested refund is an owner call; a fraudulent claim is blocked"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-CVM-KEYCUST", type: "case_study", title: "Key customer relationship risk", citation: "controls case — key-account risk", accessedDate: ACCESSED, geography: "global", businessCategory: "b2b-contractor", reliability: "high", completeness: "medium", factsUsed: ["a key-account relationship at risk is a material owner call", "concentration raises the stakes"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-CVM-CHURN", type: "review_complaint_pattern", title: "Customer churn / win-back", citation: "retention summary — churn win-back", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "medium", completeness: "medium", factsUsed: ["routine in-policy win-back outreach is fine", "a costly retention offer is an owner call"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-CVM-VENDORQUALITY", type: "sector_example", title: "Vendor reliability / quality issue", citation: "sector example — vendor quality", accessedDate: ACCESSED, geography: "global", businessCategory: "supply-logistics", reliability: "medium", completeness: "medium", factsUsed: ["a vendor quality slip threatens delivery/capacity", "a falsified quality certificate is blocked"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-CVM-VENDORPRICE", type: "finance_example", title: "Vendor price-increase negotiation", citation: "finance example — vendor price rise", accessedDate: ACCESSED, geography: "global", businessCategory: "supply-logistics", reliability: "medium", completeness: "medium", factsUsed: ["a vendor price increase hits margin", "a material contract renegotiation is an owner call"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-CVM-SINGLESOURCE", type: "failure_postmortem", title: "Single-source vendor dependency", citation: "failure post-mortem — single-source risk", accessedDate: ACCESSED, geography: "global", businessCategory: "supply-logistics", reliability: "high", completeness: "medium", factsUsed: ["over-dependence on one vendor is a supply-continuity risk", "diversification is a material owner call"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-CVM-ONBOARD", type: "regulatory_summary", title: "New vendor onboarding / vetting", citation: "regulatory summary — vendor vetting", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["a new vendor needs due-diligence/vetting", "a vendor with unclear compliance status needs professional review"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-CVM-COMPETITOR", type: "business_blog", title: "Competitor pricing pressure", citation: "market summary — competitor pricing", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "medium", completeness: "medium", factsUsed: ["a competitor price move tempts a margin-cutting response", "matching below margin is an owner call; collusion is blocked"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-CVM-DEMAND", type: "gov_sme_guidance", title: "Market demand-shift signal", citation: "SME guidance — demand shift", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["a demand shift needs validation before a response", "a material repositioning is an owner call"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-CVM-ROUTINE", type: "case_study", title: "Routine in-policy customer/vendor handling", citation: "controls case — routine handling", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "high", factsUsed: ["a routine in-policy customer/vendor action with verified data + an SOP grant proceeds with proof"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-CVM-CONSUMERLAW", type: "regulatory_summary", title: "Consumer-law boundary", citation: "regulatory summary — consumer protection", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["some refund/complaint/marketing moves cross consumer-protection law", "block until professionally cleared"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-CVM-CONTRACTLAW", type: "regulatory_summary", title: "Contract-law boundary", citation: "regulatory summary — contract terms", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["vendor/customer contract terms and disputes cross contract-law lines", "needs professional review before commitment"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-CVM-ANTICOMPETE", type: "regulatory_summary", title: "Anti-competitive / price-fixing boundary", citation: "regulatory summary — competition law", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["coordinating price with a competitor is illegal", "block any anti-competitive arrangement"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-CVM-REFUNDFRAUD", type: "failure_postmortem", title: "Fraudulent refund / chargeback claim", citation: "fraud post-mortem — refund abuse", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "high", completeness: "medium", factsUsed: ["a fraudulent refund or chargeback claim must be blocked, not paid", "unverifiable claim is no claim"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-CVM-VENDORFRAUD", type: "failure_postmortem", title: "Falsified vendor credential / quality proof", citation: "fraud post-mortem — vendor credential fraud", accessedDate: ACCESSED, geography: "global", businessCategory: "supply-logistics", reliability: "high", completeness: "medium", factsUsed: ["a falsified vendor certificate or quality proof must be blocked", "verify independently before relying on it"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-CVM-RETENTION", type: "review_complaint_pattern", title: "Customer retention / loyalty", citation: "retention summary — loyalty handling", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "medium", completeness: "medium", factsUsed: ["routine loyalty gestures within policy are fine", "a material loyalty concession is an owner call"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-CVM-CONCENTRATION", type: "finance_example", title: "Customer concentration risk", citation: "finance example — customer concentration", accessedDate: ACCESSED, geography: "global", businessCategory: "b2b-contractor", reliability: "high", completeness: "medium", factsUsed: ["a few customers being most of revenue is a concentration risk", "material dependence is an owner call"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-CVM-SLA", type: "sector_example", title: "Vendor SLA / terms", citation: "sector example — vendor SLA", accessedDate: ACCESSED, geography: "global", businessCategory: "supply-logistics", reliability: "medium", completeness: "medium", factsUsed: ["vendor SLAs define reliability expectations", "a breach or renegotiation is a material call"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-CVM-SUPPLYRISK", type: "failure_postmortem", title: "Supply continuity risk", citation: "failure post-mortem — supply disruption", accessedDate: ACCESSED, geography: "global", businessCategory: "supply-logistics", reliability: "high", completeness: "medium", factsUsed: ["a supply disruption threatens delivery/capacity", "a contingency plan is a material owner call"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-CVM-VETTING", type: "regulatory_summary", title: "Vendor due-diligence / compliance vetting", citation: "regulatory summary — vendor due diligence", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["a vendor's licences/compliance must be verified before onboarding", "unclear status needs professional review"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-CVM-PRICEMATCH", type: "finance_example", title: "Competitor price-match decision", citation: "finance example — price match", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "medium", completeness: "medium", factsUsed: ["matching a competitor below the margin floor drains profit", "a material match is an owner call"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-CVM-SEGMENT", type: "gov_sme_guidance", title: "Market segment shift", citation: "SME guidance — segment shift", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["a segment shift needs validated data before repositioning", "missing the segment data means the signal is unproven"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-CVM-FEEDBACK", type: "advice_forum", title: "Customer feedback / review handling", citation: "advice summary — review handling", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "medium", completeness: "medium", factsUsed: ["routine feedback/review responses within policy are fine", "a pattern signalling a systemic issue is an owner call"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
];

export const CUSTOMER_VENDOR_MARKET_SOURCE_BY_ID: Record<string, SourceRecord> = Object.fromEntries(
  CUSTOMER_VENDOR_MARKET_SOURCES.map((r) => [r.id, r]),
);
