/**
 * DAILY OPERATIONS source register — privacy-clean composite/sector sources for Pack 3. Validated by the
 * existing `sourceRecordSchema` (no PII, reliability/completeness tags). Sources are reused across scenarios
 * (composite sourcing, not fabrication). Every counted scenario is source-backed via one of these ids.
 */
import { sourceRecordSchema, type SourceRecord } from "../../behavioral-validation/public-cases/source-register";

const ACCESSED = "2026-07-01";
const s = (r: SourceRecord): SourceRecord => sourceRecordSchema.parse(r);

export const DAILY_OPERATIONS_SOURCES: SourceRecord[] = [
  s({ id: "SRC-DOP-ORDERS", type: "sector_example", title: "Routine order-handling flow in a small business", citation: "sector example — routine order intake and fulfilment", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "high", completeness: "high", factsUsed: ["standard order intake, confirm, fulfil, close", "reversible routine action"], factsInferred: ["safe to proceed with proof under an owner/SOP grant"], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-DOP-DELIVERY", type: "staffing_ops", title: "Pickup / delivery coordination on a normal day", citation: "operations example — routing and handoff", accessedDate: ACCESSED, geography: "global", businessCategory: "field-services", reliability: "high", completeness: "medium", factsUsed: ["scheduling pickups/deliveries", "minor slippage is routine and reversible"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-DOP-COMPLAINT", type: "review_complaint_pattern", title: "Minor customer complaint handled routinely", citation: "review-pattern composite — low-severity complaint", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "medium", completeness: "medium", factsUsed: ["small complaint, quick reversible remedy", "not a safety/legal issue"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-DOP-ATTENDANCE", type: "staffing_ops", title: "Staff attendance / punctuality on a routine day", citation: "staffing example — minor lateness pattern", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "medium", completeness: "medium", factsUsed: ["minor attendance variance", "coaching vs escalation"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-DOP-TASKS", type: "staffing_ops", title: "Daily task completion tracking", citation: "operations example — routine task closeout", accessedDate: ACCESSED, geography: "global", businessCategory: "services-ops", reliability: "high", completeness: "medium", factsUsed: ["routine tasks completed with light proof", "reversible"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-DOP-INVENTORY", type: "sector_example", title: "Small inventory / stock mismatch", citation: "operations example — minor count variance", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-inventory", reliability: "medium", completeness: "medium", factsUsed: ["small stock variance within tolerance", "recount vs investigate"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-DOP-CASH", type: "finance_example", title: "Small cash-collection / reconciliation variance", citation: "finance example — minor till variance", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "high", completeness: "medium", factsUsed: ["small reconciliation gap", "verify count before escalating"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-DOP-DISCOUNT", type: "finance_example", title: "Routine discount / price exception request", citation: "pricing example — small discretionary discount", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "high", completeness: "medium", factsUsed: ["small discount within policy", "margin-eroding beyond policy needs owner"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-DOP-EQUIPMENT", type: "staffing_ops", title: "Equipment idle / minor maintenance", citation: "operations example — routine upkeep", accessedDate: ACCESSED, geography: "global", businessCategory: "trades-repair", reliability: "medium", completeness: "medium", factsUsed: ["minor maintenance / idle time", "schedule vs run-to-failure"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-DOP-PROOFQ", type: "staffing_ops", title: "Routine proof-quality issue on a completion", citation: "quality-control example — light proof gap", accessedDate: ACCESSED, geography: "global", businessCategory: "services-ops", reliability: "high", completeness: "medium", factsUsed: ["routine completion with weak/partial proof", "request fresh proof before counting done"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-DOP-OWNERTIME", type: "gov_sme_guidance", title: "Owner time-limited routine decision", citation: "SME guidance — owner decision with a deadline", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["a routine call the owner must make by a deadline", "prepare options, do not auto-proceed"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-DOP-LEAK", type: "finance_example", title: "Small repeated operational leak", citation: "finance example — recurring small loss", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["small recurring leak that compounds", "catch and fix, do not ignore"], factsInferred: ["a small leak repeated is a real margin loss"], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-DOP-SOPGRANT", type: "case_study", title: "Owner SOP grant authorises routine reversible actions", citation: "controls case — standing SOP grant", accessedDate: ACCESSED, geography: "global", businessCategory: "services-ops", reliability: "high", completeness: "high", factsUsed: ["owner grants a standing SOP for low-risk routine steps", "proceed with proof within the grant"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-DOP-DELEGATION", type: "staffing_ops", title: "Workload-aware delegation of routine work", citation: "operations example — delegate not owner-burden", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["routine work delegated to staff/OpsIQ with proof", "owner time reserved for material calls"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-DOP-CONFIRM", type: "review_complaint_pattern", title: "Customer confirmation closes a routine query", citation: "service composite — quick confirmation", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "medium", completeness: "medium", factsUsed: ["a quick customer confirmation resolves a routine query"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-DOP-VENDOR", type: "sector_example", title: "Routine vendor / supply coordination", citation: "supply example — routine reorder", accessedDate: ACCESSED, geography: "global", businessCategory: "supply-logistics", reliability: "medium", completeness: "medium", factsUsed: ["routine reorder within normal terms"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-DOP-MARGIN", type: "finance_example", title: "Routine action with a margin implication", citation: "finance example — small margin call", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "high", completeness: "medium", factsUsed: ["a routine step that touches margin", "owner decides beyond the policy band"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-DOP-CAPACITY", type: "staffing_ops", title: "Routine capacity / scheduling call", citation: "operations example — capacity within limits", accessedDate: ACCESSED, geography: "global", businessCategory: "services-ops", reliability: "medium", completeness: "medium", factsUsed: ["scheduling within capacity", "owner decides when it strains capacity"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-DOP-COMPLIANCE", type: "regulatory_summary", title: "Routine action that touches a compliance boundary", citation: "regulatory summary — routine step near a rule", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["a routine step that crosses a compliance/legal line must not proceed", "professional review needed"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-DOP-SAFETY", type: "regulatory_summary", title: "Routine action with a staff/customer safety flag", citation: "safety summary — safety boundary on a routine step", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["a routine step with a safety flag must not proceed until cleared"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-DOP-RECONCILE", type: "finance_example", title: "Routine reconciliation needing one missing figure", citation: "finance example — pending a single input", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "medium", completeness: "low", factsUsed: ["reconciliation blocked on one missing number", "ask for it before deciding"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-DOP-RETURNS", type: "review_complaint_pattern", title: "Routine returns / refund within policy", citation: "service composite — in-policy refund", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "medium", completeness: "medium", factsUsed: ["in-policy refund proceeds with proof", "out-of-policy needs the owner"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-DOP-ROSTER", type: "staffing_ops", title: "Routine roster / shift adjustment", citation: "staffing example — minor shift swap", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "medium", completeness: "medium", factsUsed: ["routine shift swap within staffing rules"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-DOP-STOCKOUT", type: "sector_example", title: "Minor stockout / reorder trigger", citation: "inventory example — routine reorder point", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-inventory", reliability: "medium", completeness: "medium", factsUsed: ["reorder at the routine trigger point"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-DOP-UPKEEP", type: "staffing_ops", title: "Scheduled minor upkeep vs deferral", citation: "maintenance example — routine upkeep call", accessedDate: ACCESSED, geography: "global", businessCategory: "trades-repair", reliability: "medium", completeness: "medium", factsUsed: ["routine upkeep proceeds; deferral that risks downtime needs the owner"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-DOP-LEAKPROOF", type: "failure_postmortem", title: "Small leak masked by weak routine proof", citation: "post-mortem — leak hidden by light proof", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["a small recurring leak hidden behind weak proof", "demand better proof to size it"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-DOP-POLICY", type: "gov_sme_guidance", title: "Routine action bounded by an internal policy band", citation: "SME guidance — policy band for routine calls", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["inside the policy band → proceed; outside → owner or block"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-DOP-FRAUDFLAG", type: "failure_postmortem", title: "Routine step with a proof-fraud flag", citation: "post-mortem — fraud flag on a routine close", accessedDate: ACCESSED, geography: "global", businessCategory: "services-ops", reliability: "high", completeness: "medium", factsUsed: ["a routine close-out with a fraud flag must be blocked, not proceeded"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
];

export const DAILY_OPERATIONS_SOURCE_BY_ID: Record<string, SourceRecord> = Object.fromEntries(
  DAILY_OPERATIONS_SOURCES.map((r) => [r.id, r]),
);
