/**
 * FINANCE / CASH / CAPITAL ALLOCATION source register — privacy-clean composite/sector sources for Pack 4.
 * Validated by the existing `sourceRecordSchema` (no PII). Composite sourcing (not fabrication). Every counted
 * scenario is source-backed via one of these ids.
 */
import { sourceRecordSchema, type SourceRecord } from "../../behavioral-validation/public-cases/source-register";

const ACCESSED = "2026-07-01";
const s = (r: SourceRecord): SourceRecord => sourceRecordSchema.parse(r);

export const FINANCE_CASH_SOURCES: SourceRecord[] = [
  s({ id: "SRC-FIN-RUNWAY", type: "finance_example", title: "Cash runway pressure in a small business", citation: "finance example — thinning runway", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["cash runway shortening", "cash-critical calls must be owner-gated, not auto-proceeded"], factsInferred: ["protect cash before commitments"], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-FIN-PAYROLL", type: "gov_sme_guidance", title: "Payroll / staff payment obligation pressure", citation: "SME guidance — payroll obligations", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["payroll is a non-negotiable obligation", "payroll pressure must be owner-visible, never hidden"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-FIN-VENDORPAY", type: "finance_example", title: "Vendor payment prioritisation under tight cash", citation: "finance example — payables sequencing", accessedDate: ACCESSED, geography: "global", businessCategory: "b2b-contractor", reliability: "medium", completeness: "medium", factsUsed: ["prioritise payables by criticality and terms"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-FIN-RECEIVABLES", type: "finance_example", title: "Delayed receivables / B2B credit risk", citation: "finance example — overdue receivables", accessedDate: ACCESSED, geography: "global", businessCategory: "b2b-contractor", reliability: "high", completeness: "medium", factsUsed: ["overdue receivables strain cash", "B2B credit needs terms/concentration/buffer checks"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-FIN-DISCOUNT", type: "finance_example", title: "Discount vs margin decision", citation: "pricing example — discount margin impact", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "high", completeness: "medium", factsUsed: ["discounts must check margin, cash, retention, precedent, workload"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-FIN-CAPEX", type: "sector_example", title: "Capex / equipment purchase decision", citation: "capital example — equipment purchase", accessedDate: ACCESSED, geography: "global", businessCategory: "trades-repair-manufacturing", reliability: "high", completeness: "medium", factsUsed: ["capex requires runway, ROI/payback, maintenance, capacity, opportunity cost, risk"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-FIN-DEBT", type: "regulatory_summary", title: "Debt / EMI / financing pressure boundary", citation: "financing summary — debt/refinancing", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["debt/financing decisions need owner + professional review", "not final financing advice"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-FIN-RESERVE", type: "gov_sme_guidance", title: "Emergency reserve / buffer decision", citation: "SME guidance — cash buffer", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["maintain an emergency reserve", "spending the buffer is an owner decision"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-FIN-OWNERDRAW", type: "finance_example", title: "Owner draw / cash extraction decision", citation: "finance example — owner withdrawal", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["owner draw must not proceed if cash safety or obligations are at risk"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-FIN-MARGINLEAK", type: "finance_example", title: "Pricing / margin leakage", citation: "finance example — margin erosion", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "high", completeness: "medium", factsUsed: ["price below cost / silent margin leakage", "surface and owner-gate"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-FIN-TAXBOUND", type: "regulatory_summary", title: "Tax / compliance professional-boundary finance issue", citation: "regulatory summary — tax/compliance boundary", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["tax/compliance finance issues need a professional", "OpsIQ prepares, does not give final advice"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-FIN-ALLOCATION", type: "case_study", title: "Profit-first / allocation-rule decision", citation: "controls case — cash allocation rule", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "high", factsUsed: ["allocate to profit/tax/operating buckets by rule", "within-policy allocation is routine"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-FIN-TIMING", type: "finance_example", title: "Cash-flow timing mismatch", citation: "finance example — inflow/outflow timing", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "medium", completeness: "medium", factsUsed: ["timing gap between outflows and inflows"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-FIN-ADVANCE", type: "finance_example", title: "Supplier advance demand", citation: "finance example — upfront supplier payment", accessedDate: ACCESSED, geography: "global", businessCategory: "supply-logistics", reliability: "medium", completeness: "medium", factsUsed: ["supplier demands an advance", "cash risk vs supply continuity"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-FIN-CONCENTRATION", type: "finance_example", title: "B2B revenue concentration risk", citation: "finance example — customer concentration", accessedDate: ACCESSED, geography: "global", businessCategory: "b2b-contractor", reliability: "high", completeness: "medium", factsUsed: ["one customer is a large share of revenue/receivables", "concentration risk"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-FIN-WRITEOFF", type: "finance_example", title: "Receivable write-off decision", citation: "finance example — bad-debt write-off", accessedDate: ACCESSED, geography: "global", businessCategory: "b2b-contractor", reliability: "medium", completeness: "medium", factsUsed: ["writing off a bad debt hits profit and cash", "owner decision"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-FIN-SEASONAL", type: "gov_sme_guidance", title: "Seasonal cash reserve planning", citation: "SME guidance — seasonal reserves", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["reserve for the seasonal low", "plan the buffer ahead"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-FIN-REFINANCE", type: "regulatory_summary", title: "Debt restructuring / refinancing boundary", citation: "financing summary — refinancing boundary", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["restructuring/refinancing needs professional + owner review"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-FIN-INJECTION", type: "finance_example", title: "Partner / family cash injection", citation: "finance example — external cash injection", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "medium", completeness: "medium", factsUsed: ["injecting outside cash has terms/ownership implications", "owner decision"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-FIN-MIXING", type: "regulatory_summary", title: "Owner personal / business cash mixing", citation: "compliance summary — commingling risk", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["commingling personal and business cash is a compliance/accounting risk"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-FIN-ROI", type: "sector_example", title: "ROI / payback review for a spend", citation: "capital example — payback review", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["a spend needs ROI/payback and opportunity-cost review before commitment"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-FIN-UNDERPRICED", type: "finance_example", title: "Underpriced high-volume customer", citation: "finance example — volume below margin", accessedDate: ACCESSED, geography: "global", businessCategory: "b2b-contractor", reliability: "medium", completeness: "medium", factsUsed: ["a big customer priced below margin drains profit at volume"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-FIN-FRAUD", type: "failure_postmortem", title: "Financial fraud / diversion flag", citation: "fraud post-mortem — financial diversion", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["a financial transaction with a fraud/diversion flag must be blocked"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-FIN-ROUTINE", type: "case_study", title: "Routine within-threshold financial action", citation: "controls case — routine approved payment", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "high", factsUsed: ["a small within-threshold approved payment with verified data proceeds with proof"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
];

export const FINANCE_CASH_SOURCE_BY_ID: Record<string, SourceRecord> = Object.fromEntries(
  FINANCE_CASH_SOURCES.map((r) => [r.id, r]),
);
