/**
 * GROWTH / PROFIT / SCALING source register — privacy-clean composite/sector sources for Pack 6. Validated by the
 * existing `sourceRecordSchema` (no PII). Composite sourcing (not fabrication). Every counted scenario is
 * source-backed via one of these ids. The through-line: a scaling move is material and reversible-only-at-cost —
 * owner-gated by default, blocked on missing ROI/capacity/margin/cash figures, never past a legal boundary or on
 * gamed numbers, and only a small capped verified pilot proceeds.
 */
import { sourceRecordSchema, type SourceRecord } from "../../behavioral-validation/public-cases/source-register";

const ACCESSED = "2026-07-02";
const s = (r: SourceRecord): SourceRecord => sourceRecordSchema.parse(r);

export const GROWTH_PROFIT_SCALING_SOURCES: SourceRecord[] = [
  s({ id: "SRC-GRW-BRANCH", type: "sector_example", title: "Opening a new location / branch", citation: "sector example — branch expansion", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "high", completeness: "medium", factsUsed: ["a new branch is a large, mostly-irreversible capital + cash commitment", "owner-gate; prove demand, cash and capacity first"], factsInferred: ["do not open on optimism alone"], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-GRW-HIRING", type: "staffing_ops", title: "Scaling the team / new hires", citation: "staffing-ops summary — team scaling", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["hiring adds fixed cost and needs sustained capacity/demand", "owner-gate a material headcount change"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-GRW-NEWLINE", type: "sector_example", title: "Launching a new product / service line", citation: "sector example — new line launch", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "medium", completeness: "medium", factsUsed: ["a new line's margin and demand are unproven", "validate unit economics before scaling it"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-GRW-CAPEX", type: "sector_example", title: "Capacity expansion investment", citation: "capital example — capacity expansion", accessedDate: ACCESSED, geography: "global", businessCategory: "trades-repair-manufacturing", reliability: "high", completeness: "medium", factsUsed: ["expanding capacity is a capex + ROI decision", "prove payback and utilisation before committing"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-GRW-GEOEXP", type: "sector_example", title: "Market / geographic expansion", citation: "sector example — new-market entry", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "medium", completeness: "medium", factsUsed: ["a new market drains cash before it returns", "owner-gate; validate demand and legal footing first"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-GRW-PRICEUP", type: "finance_example", title: "Price increase for profit", citation: "pricing example — price increase", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "high", completeness: "medium", factsUsed: ["a material price rise affects retention and is an owner call", "small within-band rises can be routine with proof"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-GRW-MARGININIT", type: "case_study", title: "Profit margin improvement initiative", citation: "controls case — margin improvement", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "high", factsUsed: ["margin gains come from proven cost/price levers", "a small proven within-band lever is routine; material ones are owner calls"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-GRW-BULKORDER", type: "finance_example", title: "Large contract / bulk order scaling", citation: "finance example — bulk order terms", accessedDate: ACCESSED, geography: "global", businessCategory: "b2b-contractor", reliability: "medium", completeness: "medium", factsUsed: ["a large order tests margin, cash and capacity at once", "owner-gate the terms; do not accept below viable margin"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-GRW-MARKETING", type: "business_blog", title: "Scaling up a marketing channel", citation: "marketing summary — channel scale-up", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "medium", completeness: "medium", factsUsed: ["scaling spend needs proven ROI/attribution", "a small capped test can proceed; a material budget jump is an owner call"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-GRW-FRANCHISE", type: "franchise_story", title: "Partnership / franchise scaling", citation: "franchise story — franchise/partnership growth", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "medium", completeness: "medium", factsUsed: ["franchising/partnership is a structural, mostly-irreversible commitment", "owner-gate; needs legal + capacity readiness"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-GRW-ROI", type: "sector_example", title: "ROI / payback review before a growth spend", citation: "capital example — growth ROI review", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["a growth spend needs ROI/payback and opportunity-cost review", "missing the ROI figure means the decision is unproven"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-GRW-CAPACITY", type: "staffing_ops", title: "Capacity / throughput headroom before scaling", citation: "operations summary — capacity headroom", accessedDate: ACCESSED, geography: "global", businessCategory: "trades-repair-manufacturing", reliability: "high", completeness: "medium", factsUsed: ["scaling into a full bottleneck breaks quality", "relieve/prove capacity before adding volume"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-GRW-CASHRUNWAY", type: "finance_example", title: "Growth cash drain / runway", citation: "finance example — growth cash drain", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["growth consumes cash before it returns it", "protect runway; owner-gate a cash-draining scaling move"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-GRW-PILOT", type: "case_study", title: "Capped, reversible growth pilot", citation: "controls case — capped growth pilot", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "high", factsUsed: ["a small capped reversible within-capacity pilot with verified data + an SOP grant proceeds with proof"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-GRW-COMPLIANCE", type: "regulatory_summary", title: "Expansion licensing / legal boundary", citation: "regulatory summary — expansion licensing", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["a new site/line/market may need licences/permits/approvals", "OpsIQ prepares; the boundary needs professional review"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-GRW-LABOUR", type: "regulatory_summary", title: "Hiring / labour-law boundary", citation: "regulatory summary — labour-law boundary", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["hiring/contract structures cross labour-law lines", "needs professional review, not an auto-decision"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-GRW-CONSUMERLAW", type: "regulatory_summary", title: "Pricing / consumer-law boundary", citation: "regulatory summary — pricing consumer-law", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["some pricing/promo moves cross consumer-protection lines", "block until professionally cleared"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-GRW-FRANCHISELAW", type: "regulatory_summary", title: "Franchise disclosure / partnership legal boundary", citation: "regulatory summary — franchise disclosure", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["franchising/partnership has disclosure + contract-law duties", "needs professional review before commitment"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-GRW-FRAUD", type: "failure_postmortem", title: "Gamed growth / projection numbers", citation: "fraud post-mortem — inflated projections", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["a scaling case built on gamed or inflated numbers must be blocked", "unverifiable proof is no proof"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-GRW-ATTRIBUTION", type: "failure_postmortem", title: "Marketing attribution / fake-lead risk", citation: "fraud post-mortem — inflated attribution", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "medium", completeness: "medium", factsUsed: ["scaling on inflated attribution or fake leads is a proof-fraud risk", "block until independently verified"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-GRW-DEMAND", type: "gov_sme_guidance", title: "Demand / market validation before scaling", citation: "SME guidance — demand validation", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["scaling needs validated, sustained demand", "missing demand evidence means the decision is unproven"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-GRW-UNITECON", type: "gov_sme_guidance", title: "Unit economics before scaling", citation: "SME guidance — unit economics", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["scaling a loss multiplies the loss", "prove positive unit economics before scaling"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-GRW-CONTRACTTERMS", type: "finance_example", title: "Bulk contract terms / margin", citation: "finance example — contract terms margin", accessedDate: ACCESSED, geography: "global", businessCategory: "b2b-contractor", reliability: "medium", completeness: "medium", factsUsed: ["bulk-order terms can hide a below-cost margin", "owner-gate the terms; re-quote to a viable margin"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-GRW-OVEREXPANSION", type: "failure_postmortem", title: "Over-expansion failure", citation: "failure post-mortem — over-expansion", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["scaling faster than cash/capacity is a classic failure mode", "cap growth to proven, reliable throughput"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
];

export const GROWTH_PROFIT_SCALING_SOURCE_BY_ID: Record<string, SourceRecord> = Object.fromEntries(
  GROWTH_PROFIT_SCALING_SOURCES.map((r) => [r.id, r]),
);
