/**
 * LOCAL / LEGAL / PROFESSIONAL-BOUNDARY source register — privacy-clean composite/sector sources for Pack 8.
 * Validated by the existing `sourceRecordSchema` (no PII). Composite sourcing (not fabrication). Every counted
 * scenario is source-backed via one of these ids. The through-line: OpsIQ PREPARES legal/tax/compliance matters
 * and routes to the owner + a qualified professional — it never gives final advice and never self-clears a
 * professional boundary; fabricated documents / falsified books are blocked as fraud.
 */
import { sourceRecordSchema, type SourceRecord } from "../../behavioral-validation/public-cases/source-register";

const ACCESSED = "2026-07-02";
const s = (r: SourceRecord): SourceRecord => sourceRecordSchema.parse(r);

export const LOCAL_LEGAL_BOUNDARY_SOURCES: SourceRecord[] = [
  s({ id: "SRC-LLB-TAX", type: "regulatory_summary", title: "Tax / GST filing treatment", citation: "regulatory summary — tax/GST treatment", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["tax treatment questions need a qualified accountant", "OpsIQ prepares the records, does not give final tax advice"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-LLB-LABOR", type: "regulatory_summary", title: "Employment / labour-law issue", citation: "regulatory summary — labour law", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["termination/classification/wage questions cross labour law", "needs professional/legal review before action"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-LLB-LICENSE", type: "regulatory_summary", title: "Licensing / permit / registration", citation: "regulatory summary — licensing", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["operating without the right licence/permit is a compliance breach", "a routine scheduled renewal is administrative; a new/unclear licence needs review"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-LLB-CONTRACT", type: "regulatory_summary", title: "Contract / legal dispute", citation: "regulatory summary — contract dispute", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["a contract dispute needs a lawyer", "OpsIQ organises the facts; settlement/litigation is an owner + legal call"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-LLB-REGULATORY", type: "regulatory_summary", title: "Regulatory compliance / inspection", citation: "regulatory summary — inspection", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["a regulatory inspection/notice needs professional handling", "prepare the records; do not self-clear a finding"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-LLB-PRIVACY", type: "regulatory_summary", title: "Data privacy / customer records", citation: "regulatory summary — data privacy", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["customer-data handling/breach crosses privacy law", "needs professional/legal review, not an auto-decision"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-LLB-SAFETY", type: "regulatory_summary", title: "Health / safety regulation", citation: "regulatory summary — health & safety", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["health/safety obligations are legally mandated", "a safety finding needs professional remediation, not self-clearance"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-LLB-IP", type: "regulatory_summary", title: "Intellectual property / trademark", citation: "regulatory summary — IP/trademark", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["trademark/IP registration and infringement need an IP professional", "OpsIQ prepares; enforcement/registration is an owner + legal call"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-LLB-AUDIT", type: "regulatory_summary", title: "Accounting / audit professional boundary", citation: "regulatory summary — accounting/audit", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["accounting treatment and audits need a qualified accountant/auditor", "OpsIQ prepares the books; it does not sign off accounts"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-LLB-ZONING", type: "regulatory_summary", title: "Local authority / zoning / municipal", citation: "regulatory summary — zoning/municipal", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["zoning/municipal rules govern where/how you operate", "a zoning question needs the local authority + professional review"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-LLB-PROFESSIONAL", type: "gov_sme_guidance", title: "Professional-boundary principle: prepare, don't advise", citation: "SME guidance — when to get a professional", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "high", factsUsed: ["a tool prepares and organises; final legal/tax/HR advice needs a qualified professional", "know the boundary and route to one"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-LLB-RECORDS", type: "gov_sme_guidance", title: "Records / documentation needed for a legal matter", citation: "SME guidance — legal recordkeeping", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["a legal/tax decision needs the underlying records/filings", "missing documentation means the matter is unproven"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-LLB-ROUTINE", type: "case_study", title: "Routine professional-prepared in-policy filing", citation: "controls case — accountant-prepared filing", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "high", factsUsed: ["a routine filing already prepared/approved by the professional, within policy, proceeds with proof"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-LLB-TAXFRAUD", type: "failure_postmortem", title: "Fabricated tax documents", citation: "fraud post-mortem — fabricated tax records", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["fabricated invoices or tax documents must be blocked, not filed", "unverifiable records are no records"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-LLB-BOOKSFRAUD", type: "failure_postmortem", title: "Falsified books / cooked accounts", citation: "fraud post-mortem — falsified books", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["falsified books must be blocked and surfaced, never relied on for a filing or audit"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-LLB-SETTLEMENT", type: "finance_example", title: "Legal settlement cost decision", citation: "finance example — settlement cost", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "medium", completeness: "medium", factsUsed: ["settle-vs-fight has a material cost", "the decision is the owner's, informed by legal counsel"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-LLB-FILING", type: "regulatory_summary", title: "Statutory filing deadline", citation: "regulatory summary — statutory deadline", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["a statutory filing has a hard deadline and penalties", "prepare it and route treatment questions to the professional"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-LLB-PENALTY", type: "finance_example", title: "Penalty / fine exposure", citation: "finance example — penalty exposure", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "medium", completeness: "medium", factsUsed: ["non-compliance carries fines/penalties", "the exposure and response are an owner + professional call"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-LLB-CONSENT", type: "regulatory_summary", title: "Data consent / breach obligation", citation: "regulatory summary — data consent/breach", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["consent and breach-notification duties are legally defined", "a breach needs professional/legal handling and notification"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-LLB-INSPECTION", type: "regulatory_summary", title: "Inspection readiness", citation: "regulatory summary — inspection readiness", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["preparing records for an inspection is administrative", "responding to a finding needs professional handling"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-LLB-WORKERCLASS", type: "regulatory_summary", title: "Worker classification", citation: "regulatory summary — worker classification", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["contractor-vs-employee classification is a legal determination", "misclassification carries liability; needs professional review"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-LLB-TRADEMARK", type: "regulatory_summary", title: "Trademark registration / infringement", citation: "regulatory summary — trademark", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["registering or enforcing a trademark needs an IP professional", "an infringement claim needs legal review"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-LLB-PERMITRENEWAL", type: "case_study", title: "Standard permit renewal", citation: "controls case — scheduled permit renewal", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "high", factsUsed: ["a scheduled, unchanged permit/licence renewal within policy is routine administrative work"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-LLB-DISCLOSURE", type: "regulatory_summary", title: "Legal disclosure obligation", citation: "regulatory summary — disclosure duty", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["mandatory disclosures have legal form and timing", "getting them wrong is a compliance breach; route to a professional"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
];

export const LOCAL_LEGAL_BOUNDARY_SOURCE_BY_ID: Record<string, SourceRecord> = Object.fromEntries(
  LOCAL_LEGAL_BOUNDARY_SOURCES.map((r) => [r.id, r]),
);
