/**
 * STAFF / PROOF / ANTI-GAMING source register — privacy-clean composite/sector sources for Pack 2. Validated by
 * the existing `sourceRecordSchema` (no PII, reliability/completeness tags). Sources are reused across scenarios
 * (composite sourcing, not fabrication). Every counted scenario is source-backed via one of these ids.
 */
import { sourceRecordSchema, type SourceRecord } from "../../behavioral-validation/public-cases/source-register";

const ACCESSED = "2026-07-01";
const s = (r: SourceRecord): SourceRecord => sourceRecordSchema.parse(r);

export const STAFF_PROOF_SOURCES: SourceRecord[] = [
  s({ id: "SRC-SPA-FAKECOMPLETE", type: "failure_postmortem", title: "Fake task-completion marked done without real work", citation: "field-ops post-mortem — completion claimed, work not performed", accessedDate: ACCESSED, geography: "global", businessCategory: "services-ops", reliability: "high", completeness: "medium", factsUsed: ["task marked complete with no verifiable evidence", "customer later reports work not done"], factsInferred: ["completion must require independent proof"], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-SPA-REUSEDPHOTO", type: "review_complaint_pattern", title: "Reused or stale photo submitted as fresh completion proof", citation: "review-pattern composite — recycled proof image", accessedDate: ACCESSED, geography: "global", businessCategory: "field-services", reliability: "medium", completeness: "medium", factsUsed: ["same or old photo submitted across jobs", "no fresh timestamp/location"], factsInferred: ["proof must be fresh and job-specific"], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-SPA-STAGEDPROOF", type: "failure_postmortem", title: "Staged / misleading proof that misrepresents the real state", citation: "quality-audit post-mortem — staged evidence", accessedDate: ACCESSED, geography: "global", businessCategory: "trades-repair", reliability: "high", completeness: "medium", factsUsed: ["evidence staged to imply completion", "underlying defect remains"], factsInferred: ["independent verification required before acceptance"], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-SPA-RUBBERSTAMP", type: "staffing_ops", title: "Manager rubber-stamping weak proof without checking", citation: "supervision study — approvals without verification", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "medium", completeness: "medium", factsUsed: ["manager approves without inspecting proof", "defective proof passes review"], factsInferred: ["approval cannot override hard proof defects"], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-SPA-COLLUSION", type: "failure_postmortem", title: "Staff-manager collusion to pass unverifiable work", citation: "internal-fraud post-mortem — collusive sign-off", accessedDate: ACCESSED, geography: "global", businessCategory: "services-ops", reliability: "high", completeness: "medium", factsUsed: ["staff and approver collude on sign-off", "single chain of trust compromised"], factsInferred: ["independent (out-of-chain) verification required"], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-SPA-DELAYEDPROOF", type: "staffing_ops", title: "Delayed / after-the-fact proof reconstructed later", citation: "operations example — proof produced long after the task", accessedDate: ACCESSED, geography: "global", businessCategory: "field-services", reliability: "medium", completeness: "medium", factsUsed: ["proof supplied well after completion window", "reconstruction not contemporaneous"], factsInferred: ["fresh contemporaneous proof required"], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-SPA-CONTRADICT", type: "review_complaint_pattern", title: "Proof contradicts customer / vendor / system records", citation: "dispute composite — proof vs external records mismatch", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "high", completeness: "medium", factsUsed: ["staff proof conflicts with customer or system data", "mismatch unexplained"], factsInferred: ["contradiction must trigger dispute/confirmation"], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-SPA-SELECTIVE", type: "failure_postmortem", title: "Selective reporting that omits the bad facts", citation: "reporting post-mortem — favourable-only reporting", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "medium", completeness: "medium", factsUsed: ["only favourable metrics reported", "adverse facts omitted"], factsInferred: ["omitted adverse data must be requested"], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-SPA-EXCUSE", type: "staffing_ops", title: "Repeated false-excuse pattern masking non-performance", citation: "supervision composite — recurring excuse pattern", accessedDate: ACCESSED, geography: "global", businessCategory: "services-ops", reliability: "medium", completeness: "low", factsUsed: ["recurring excuses substitute for delivery", "pattern across periods"], factsInferred: ["repeated excuses trigger pattern review"], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-SPA-TASKSPLIT", type: "sector_example", title: "Task splitting / metric gaming to inflate counts", citation: "productivity example — unit gaming", accessedDate: ACCESSED, geography: "global", businessCategory: "operations", reliability: "medium", completeness: "medium", factsUsed: ["one task split into many to inflate counts", "throughput metric distorted"], factsInferred: ["gamed counts must not inflate performance"], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-SPA-WORKLOADGAME", type: "staffing_ops", title: "Workload gaming / unfair burden shifting", citation: "staffing study — burden shifted, overload hidden", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "medium", completeness: "medium", factsUsed: ["burden shifted onto some staff", "overload concealed in aggregates"], factsInferred: ["overburdening must be surfaced, not hidden"], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-SPA-SOPDRIFT", type: "regulatory_summary", title: "Training non-compliance / SOP drift over time", citation: "compliance summary — procedure drift", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["staff diverge from required SOP", "training lapsed or skipped"], factsInferred: ["drift triggers corrective training/reassessment"], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-SPA-PROOFQUALITY", type: "staffing_ops", title: "Proof-quality grading for completion evidence", citation: "quality-control example — proof grading rubric", accessedDate: ACCESSED, geography: "global", businessCategory: "services-ops", reliability: "high", completeness: "high", factsUsed: ["weak proof lowers confidence", "grade drives acceptance/dispute"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-SPA-INDEPVERIFY", type: "sector_example", title: "Independent verification breaks a single chain of trust", citation: "controls example — out-of-chain verification", accessedDate: ACCESSED, geography: "global", businessCategory: "operations", reliability: "high", completeness: "medium", factsUsed: ["independent check catches collusive sign-off", "second source required"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-SPA-CUSTCONFIRM", type: "review_complaint_pattern", title: "Customer confirmation resolves a disputed completion", citation: "service composite — customer confirmation", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "medium", completeness: "medium", factsUsed: ["customer confirmation settles disputed proof", "confirmation is out-of-chain"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-SPA-VENDORCONFIRM", type: "finance_example", title: "Vendor / system record confirms or refutes a claim", citation: "reconciliation example — vendor record cross-check", accessedDate: ACCESSED, geography: "global", businessCategory: "b2b-contractor", reliability: "high", completeness: "medium", factsUsed: ["vendor/system record cross-checks the claim", "mismatch flagged"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-SPA-TIMESTAMP", type: "staffing_ops", title: "Missing timestamp / geotag on completion proof", citation: "field-ops example — non-contemporaneous proof", accessedDate: ACCESSED, geography: "global", businessCategory: "field-services", reliability: "medium", completeness: "medium", factsUsed: ["proof lacks timestamp/location", "freshness unverifiable"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-SPA-DUPLICATE", type: "failure_postmortem", title: "Duplicate proof reused across distinct jobs", citation: "audit post-mortem — duplicated evidence hash", accessedDate: ACCESSED, geography: "global", businessCategory: "services-ops", reliability: "high", completeness: "medium", factsUsed: ["identical proof reused for different jobs", "duplication detectable"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-SPA-METRICINFLATE", type: "sector_example", title: "Inflated performance metric from gamed inputs", citation: "performance example — metric inflation", accessedDate: ACCESSED, geography: "global", businessCategory: "operations", reliability: "medium", completeness: "medium", factsUsed: ["headline metric inflated by gaming", "underlying output unchanged"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-SPA-OVERLOAD", type: "staffing_ops", title: "Hidden overload from burden shifting", citation: "staffing example — concealed overload", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "medium", completeness: "medium", factsUsed: ["individual overload hidden in team totals", "burnout risk understated"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-SPA-TRAININGGAP", type: "regulatory_summary", title: "Training gap producing unsafe shortcut behaviour", citation: "compliance example — training gap", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["untrained staff take unsafe shortcuts", "SOP not followed"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-SPA-VERIFIEDGOOD", type: "case_study", title: "Verified fresh proof accepted under an owner SOP grant", citation: "controls case — clean verified completion", accessedDate: ACCESSED, geography: "global", businessCategory: "services-ops", reliability: "high", completeness: "high", factsUsed: ["fresh, job-specific, cross-checked proof accepted", "owner SOP grant authorises the step"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
];

export const STAFF_PROOF_SOURCE_BY_ID: Record<string, SourceRecord> = Object.fromEntries(
  STAFF_PROOF_SOURCES.map((r) => [r.id, r]),
);
