/**
 * UGLY / TAIL-RISK / CRISIS source register — privacy-clean composite/sector sources for Pack 9. Validated by the
 * existing `sourceRecordSchema` (no PII). Composite sourcing (not fabrication). Every counted scenario is
 * source-backed via one of these ids. The through-line: in a crisis OpsIQ does NOT act rashly — it blocks unsafe/
 * irreversible moves and legal/safety/insolvency boundaries, owner-gates the material response, gets the facts, and
 * allows only routine reversible containment; confirmed fraud/theft is blocked.
 */
import { sourceRecordSchema, type SourceRecord } from "../../behavioral-validation/public-cases/source-register";

const ACCESSED = "2026-07-02";
const s = (r: SourceRecord): SourceRecord => sourceRecordSchema.parse(r);

export const UGLY_TAIL_RISK_CRISIS_SOURCES: SourceRecord[] = [
  s({ id: "SRC-UTR-CASHCOLLAPSE", type: "failure_postmortem", title: "Cash collapse / insolvency risk", citation: "failure post-mortem — cash collapse", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["a cash collapse threatens survival and triggers insolvency duties", "protect cash; trading-while-insolvent is a legal line"], factsInferred: ["do not spend into the ground"], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-UTR-INSOLVENCY", type: "regulatory_summary", title: "Insolvency legal duties", citation: "regulatory summary — insolvency duties", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["insolvency triggers director/owner legal duties", "needs professional/legal handling, not self-clearance"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-UTR-FRAUD", type: "failure_postmortem", title: "Fraud / theft / embezzlement", citation: "fraud post-mortem — internal fraud", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["confirmed fraud/theft must be blocked and escalated, never acted on as normal", "preserve evidence; involve professionals"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-UTR-EMBEZZLE", type: "failure_postmortem", title: "Embezzlement / misappropriation", citation: "fraud post-mortem — embezzlement", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["misappropriated funds are a fraud pattern", "block, preserve records, and escalate to owner + professional"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-UTR-KEYPERSON", type: "failure_postmortem", title: "Key-person loss / founder dependency", citation: "failure post-mortem — key-person loss", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["losing a key person/founder is a continuity risk", "the response is a material owner call"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-UTR-CUSTOMERLOSS", type: "failure_postmortem", title: "Major customer loss / revenue shock", citation: "failure post-mortem — major account loss", accessedDate: ACCESSED, geography: "global", businessCategory: "b2b-contractor", reliability: "high", completeness: "medium", factsUsed: ["losing a major customer is a revenue shock", "the response (cost/cash/repricing) is a material owner call"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-UTR-SUPPLY", type: "failure_postmortem", title: "Supply-chain disruption / shortage", citation: "failure post-mortem — supply disruption", accessedDate: ACCESSED, geography: "global", businessCategory: "supply-logistics", reliability: "high", completeness: "medium", factsUsed: ["a supply shock threatens delivery/capacity", "contingency sourcing is a material owner call"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-UTR-SAFETY", type: "regulatory_summary", title: "Safety incident / injury", citation: "regulatory summary — workplace safety incident", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["a safety incident/injury has mandatory reporting + remediation duties", "block self-clearance; involve professionals/authorities"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-UTR-LAWSUIT", type: "regulatory_summary", title: "Legal lawsuit / regulatory action", citation: "regulatory summary — lawsuit/enforcement", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["a lawsuit or regulatory action needs a lawyer", "OpsIQ organises facts; the response is owner + legal"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-UTR-REPUTATION", type: "review_complaint_pattern", title: "Reputational crisis / public backlash", citation: "reputation summary — public backlash", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "medium", completeness: "medium", factsUsed: ["a public backlash can escalate fast", "the response is a material owner call; do not react rashly"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-UTR-DISASTER", type: "cyber_continuity", title: "Natural disaster / business continuity", citation: "continuity summary — disaster recovery", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["a disaster disrupts operations and capacity", "safety first; continuity/restart is a material owner call"], factsInferred: [], factsSyntheticallyVaried: ["Generalized to fire/flood/quake continuity"], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-UTR-DATABREACH", type: "cyber_continuity", title: "Data breach / cyber incident", citation: "cyber summary — data breach response", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["a data breach has legal notification duties + technical containment", "block self-clearance; involve professionals; owner decides disclosure"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-UTR-CONTAINMENT", type: "case_study", title: "Routine reversible immediate containment", citation: "controls case — crisis containment step", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "high", factsUsed: ["a routine, reversible, immediate-containment step within the SOP (e.g. secure the site, freeze an account, back up data) proceeds with proof"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-UTR-EMERGENCYCASH", type: "finance_example", title: "Emergency cash triage", citation: "finance example — emergency cash triage", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["in a cash crisis, triage obligations and protect the essential", "major moves are owner calls"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-UTR-FACTS", type: "gov_sme_guidance", title: "Getting the crisis facts before acting", citation: "SME guidance — crisis fact-finding", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["a crisis response needs the facts (scope, cause, exposure) first", "acting on missing facts makes it worse"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-UTR-COVERUP", type: "failure_postmortem", title: "Crisis cover-up / concealment", citation: "fraud post-mortem — incident concealment", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["concealing an incident/loss is a fraud pattern that must be blocked", "surface and escalate, never hide"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-UTR-CREDITOR", type: "regulatory_summary", title: "Creditor / obligation duties in distress", citation: "regulatory summary — creditor duties", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["distressed businesses have creditor-treatment duties", "preferential/unlawful payments are a legal line"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-UTR-INSURANCE", type: "case_study", title: "Insurance / claim in a crisis", citation: "controls case — crisis insurance claim", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "medium", completeness: "medium", factsUsed: ["a crisis may trigger an insurance claim with notice requirements", "the claim decision is an owner call with the insurer/broker"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-UTR-COMMS", type: "business_blog", title: "Crisis communications", citation: "comms summary — crisis communication", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "medium", completeness: "medium", factsUsed: ["public/customer communications in a crisis carry legal + reputational risk", "the message is a material owner call"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-UTR-CONTINUITY", type: "cyber_continuity", title: "Business continuity plan", citation: "continuity summary — BCP activation", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["activating a continuity plan restores critical operations", "scope/cost of restart is a material owner call"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-UTR-BACKUP", type: "staffing_ops", title: "Key-person backup / succession", citation: "operations summary — succession/backup", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "medium", completeness: "medium", factsUsed: ["cross-training and succession reduce key-person risk", "a material succession decision is an owner call"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-UTR-CONCENTRATIONSHOCK", type: "finance_example", title: "Revenue concentration shock", citation: "finance example — concentration shock", accessedDate: ACCESSED, geography: "global", businessCategory: "b2b-contractor", reliability: "high", completeness: "medium", factsUsed: ["a concentrated revenue base amplifies a customer-loss shock", "the recovery plan is an owner call"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-UTR-RECALL", type: "regulatory_summary", title: "Product recall / defect", citation: "regulatory summary — product recall", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["a product defect/recall has mandatory safety + notification duties", "block self-clearance; involve professionals/authorities"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-UTR-RANSOM", type: "cyber_continuity", title: "Ransomware / extortion demand", citation: "cyber summary — ransomware", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["a ransomware/extortion demand has legal + security implications", "block a rash payment; involve professionals/authorities; owner decides"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
];

export const UGLY_TAIL_RISK_CRISIS_SOURCE_BY_ID: Record<string, SourceRecord> = Object.fromEntries(
  UGLY_TAIL_RISK_CRISIS_SOURCES.map((r) => [r.id, r]),
);
