/**
 * UNKNOWN / OOD source register — privacy-clean composite/sector sources for the Unknown/Novel/OOD pack.
 * Validated by the existing `sourceRecordSchema` (no PII, reliability/completeness tags). Sources are reused
 * across scenarios (as the baseline corpus reuses its 11 patterns) — honest composite sourcing, not fabrication.
 */
import { sourceRecordSchema, type SourceRecord } from "../../behavioral-validation/public-cases/source-register";

const ACCESSED = "2026-07-01";
const s = (r: SourceRecord): SourceRecord => sourceRecordSchema.parse(r);

export const UNKNOWN_OOD_SOURCES: SourceRecord[] = [
  s({ id: "SRC-OOD-NEWMODEL", type: "failure_postmortem", title: "Novel business-model pivots that outran their unit economics", citation: "composite SME post-mortem — unproven model, thin data", accessedDate: ACCESSED, geography: "global", businessCategory: "misc-SMB", reliability: "medium", completeness: "low", factsUsed: ["novel model with no historical baseline", "owner cannot yet price or forecast reliably"], factsInferred: ["decisions need staged proof before scaling"], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-OOD-NEWSERVICE", type: "sector_example", title: "Adding an unfamiliar service line with unknown demand", citation: "sector example — new service, no demand signal", accessedDate: ACCESSED, geography: "global", businessCategory: "services", reliability: "medium", completeness: "low", factsUsed: ["new service category with no prior sales data"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-OOD-NEWEQUIP", type: "staffing_ops", title: "New equipment/process with unproven throughput", citation: "operations example — unproven capacity", accessedDate: ACCESSED, geography: "global", businessCategory: "trades-repair-manufacturing", reliability: "medium", completeness: "medium", factsUsed: ["new equipment throughput not yet measured"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-OOD-JURIS", type: "regulatory_summary", title: "New-jurisdiction / local-rule uncertainty requiring professional review", citation: "regulatory summary — local rules unclear", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["local rule applicability uncertain", "professional/licensing review needed"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-OOD-B2BTERMS", type: "finance_example", title: "Unusual B2B contract terms with unclear cash impact", citation: "B2B receivables example — atypical terms", accessedDate: ACCESSED, geography: "global", businessCategory: "b2b-contractor", reliability: "high", completeness: "medium", factsUsed: ["non-standard payment/penalty terms", "cash impact uncertain"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-OOD-CUSTBEHAV", type: "review_complaint_pattern", title: "Strange/unexplained customer-behaviour shift", citation: "review-pattern composite — anomalous demand/return behaviour", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "medium", completeness: "low", factsUsed: ["unexplained shift in customer behaviour"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-OOD-STAFFGAME", type: "failure_postmortem", title: "Previously-unseen staff/proof manipulation pattern", citation: "fraud post-mortem — novel gaming of completion proof", accessedDate: ACCESSED, geography: "global", businessCategory: "services-ops", reliability: "high", completeness: "medium", factsUsed: ["novel manipulation of completion/proof records"], factsInferred: ["independent verification required"], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-OOD-VENDOR", type: "sector_example", title: "Unusual vendor/supply pattern with unclear reliability", citation: "supply example — atypical vendor behaviour", accessedDate: ACCESSED, geography: "global", businessCategory: "supply-logistics", reliability: "medium", completeness: "low", factsUsed: ["atypical vendor terms or unverifiable supply claims"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-OOD-SHOCK", type: "regulatory_summary", title: "Sudden external shock (input cost / demand / disruption)", citation: "continuity study — sudden external shock", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["sudden external shock with uncertain magnitude"], factsInferred: ["protect runway before commitments"], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-OOD-URGENT", type: "advice_forum", title: "Contradictory/incomplete urgent owner question", citation: "owner-forum composite — conflicting incomplete inputs", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "low", completeness: "low", factsUsed: ["owner question is urgent, contradictory, and missing key facts"], factsInferred: ["ask for the specific missing facts before deciding"], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-OOD-WEAKANALOGY", type: "business_blog", title: "Pattern-adjacent case where the closest analogy is weak", citation: "operations blog — analogy may mislead", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "medium", completeness: "low", factsUsed: ["closest known pattern differs in a material way"], factsInferred: ["label the analogy as weak; verify before acting"], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-OOD-CYBERNOVEL", type: "cyber_continuity", title: "Novel cyber/payment anomaly of unknown nature", citation: "cyber continuity — unrecognised payment anomaly", accessedDate: ACCESSED, geography: "global", businessCategory: "ecommerce", reliability: "high", completeness: "medium", factsUsed: ["unrecognised payment/data anomaly", "verify before any payout"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-OOD-LICENCE", type: "regulatory_summary", title: "Possible new licence/permit requirement", citation: "regulatory summary — licence applicability unclear", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["a licence/permit may now be required"], factsInferred: ["obtain written professional review"], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-OOD-DEMANDSPIKE", type: "sector_example", title: "Unexplained demand spike of uncertain durability", citation: "sector example — spike may not persist", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "medium", completeness: "low", factsUsed: ["sudden demand spike of unknown durability"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-OOD-PRICINGNOVEL", type: "finance_example", title: "Novel pricing model with unclear margin", citation: "pricing example — margin unproven", accessedDate: ACCESSED, geography: "global", businessCategory: "services", reliability: "medium", completeness: "low", factsUsed: ["novel pricing structure, fully-loaded margin unknown"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-OOD-PARTNERSHIP", type: "case_study", title: "Unfamiliar partnership/revenue-share structure", citation: "case study — novel partnership terms", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "medium", completeness: "low", factsUsed: ["unfamiliar revenue-share/partnership structure"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-OOD-HEALTHSAFETY", type: "regulatory_summary", title: "Possible health/safety boundary in a novel process", citation: "regulatory summary — safety review needed", accessedDate: ACCESSED, geography: "global", businessCategory: "care-food-trades", reliability: "high", completeness: "medium", factsUsed: ["novel process may cross a health/safety boundary"], factsInferred: ["pause and get professional review"], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-OOD-DATASPARSE", type: "advice_forum", title: "Decision requested with almost no persisted data", citation: "owner-forum — sparse data, big ask", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "low", completeness: "low", factsUsed: ["material decision requested with sparse/absent records"], factsInferred: ["request the specific critical records first"], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-OOD-VENDORFRAUD", type: "failure_postmortem", title: "Unverifiable vendor claim of a novel kind", citation: "fraud post-mortem — novel unverifiable vendor claim", accessedDate: ACCESSED, geography: "global", businessCategory: "supply-logistics", reliability: "high", completeness: "medium", factsUsed: ["vendor makes an unverifiable novel claim"], factsInferred: ["require independent verification before paying"], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-OOD-CONTRACTCLAUSE", type: "finance_example", title: "Ambiguous contract clause of uncertain effect", citation: "contract example — clause ambiguity", accessedDate: ACCESSED, geography: "global", businessCategory: "b2b-contractor", reliability: "medium", completeness: "medium", factsUsed: ["a contract clause has an uncertain legal/cash effect"], factsInferred: ["professional review before signing"], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-OOD-CHANNELSHIFT", type: "business_blog", title: "Sudden sales-channel shift of unknown economics", citation: "operations blog — channel shift, unknown economics", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-ecommerce", reliability: "medium", completeness: "low", factsUsed: ["sales shifting to a new channel with unknown economics"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-OOD-STAFFSKILL", type: "staffing_ops", title: "Novel staffing/skill requirement of unclear feasibility", citation: "staffing example — new skill need, feasibility unclear", accessedDate: ACCESSED, geography: "global", businessCategory: "services-ops", reliability: "medium", completeness: "low", factsUsed: ["a novel skill/staffing need of uncertain feasibility"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
];

/** id → source (for lookup during scenario authoring). */
export const OOD_SOURCE_BY_ID: Record<string, SourceRecord> = Object.fromEntries(UNKNOWN_OOD_SOURCES.map((r) => [r.id, r]));
