/**
 * WEEKLY MANAGEMENT / TREND source register — privacy-clean composite/sector sources for Pack 5. Validated by the
 * existing `sourceRecordSchema` (no PII). Composite sourcing (not fabrication). Every counted scenario is
 * source-backed via one of these ids. The through-line: a weekly metric moving over time is a SIGNAL that must be
 * confirmed against a baseline before it is acted on — never auto-acted, never gamed, never past a compliance line.
 */
import { sourceRecordSchema, type SourceRecord } from "../../behavioral-validation/public-cases/source-register";

const ACCESSED = "2026-07-02";
const s = (r: SourceRecord): SourceRecord => sourceRecordSchema.parse(r);

export const WEEKLY_MANAGEMENT_TREND_SOURCES: SourceRecord[] = [
  s({ id: "SRC-WKY-REVDRIFT", type: "finance_example", title: "Weekly revenue drifting down over several weeks", citation: "finance example — sustained weekly revenue decline", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["a multi-week revenue decline is a trend, not a single bad week", "confirm against a baseline before acting"], factsInferred: ["react to proven drift, not noise"], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-WKY-MARGINDRIFT", type: "finance_example", title: "Gross margin drifting down week over week", citation: "finance example — silent margin erosion trend", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "high", completeness: "medium", factsUsed: ["gross margin can erode silently across weeks", "needs the cost basis and per-line margins to confirm"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-WKY-COMPLAINT", type: "review_complaint_pattern", title: "Customer complaint volume trending up", citation: "complaint-pattern summary — rising weekly complaints", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "medium", completeness: "medium", factsUsed: ["a rising complaint trend signals a systemic quality issue", "handle the trend, do not spend on acquisition over it"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-WKY-REWORK", type: "staffing_ops", title: "Rework / redo rate trending up", citation: "operations summary — rising rework trend", accessedDate: ACCESSED, geography: "global", businessCategory: "trades-repair-manufacturing", reliability: "medium", completeness: "medium", factsUsed: ["rising rework wastes capacity and margin", "confirm the rework count against the job baseline"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-WKY-PRODUCTIVITY", type: "staffing_ops", title: "Staff productivity / output per shift drifting", citation: "staffing-ops summary — productivity drift", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "medium", completeness: "medium", factsUsed: ["output per shift can drift down gradually", "confirm against staffing and hours before concluding"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-WKY-DELIVERY", type: "sector_example", title: "On-time delivery / turnaround slipping", citation: "sector example — delivery-delay trend", accessedDate: ACCESSED, geography: "global", businessCategory: "supply-logistics", reliability: "medium", completeness: "medium", factsUsed: ["on-time % slipping over weeks is a capacity/scheduling trend", "confirm the on-time baseline first"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-WKY-PROOFCOMP", type: "regulatory_summary", title: "Proof-submission / compliance completeness trending down", citation: "regulatory summary — compliance-completeness trend", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["a falling proof/compliance-completeness trend crosses a professional-review boundary", "block until reviewed, do not self-clear"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-WKY-INVENTORY", type: "finance_example", title: "Inventory / consumable usage drifting above benchmark", citation: "finance example — consumable-usage drift", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "medium", completeness: "medium", factsUsed: ["consumable usage per job creeping above benchmark leaks margin", "confirm usage against the benchmark and output"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-WKY-RETENTION", type: "review_complaint_pattern", title: "Repeat-customer / retention rate declining", citation: "retention-pattern summary — repeat-rate decline", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "medium", completeness: "medium", factsUsed: ["a declining repeat-customer rate is a leading revenue risk", "confirm the cohort baseline before acting"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-WKY-MARKETING", type: "business_blog", title: "Marketing campaign underperforming its target", citation: "marketing summary — campaign underperformance", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "medium", completeness: "medium", factsUsed: ["a campaign below its lead/ROI target is a spend-efficiency decision", "confirm attribution before scaling or cutting"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-WKY-BASELINE", type: "gov_sme_guidance", title: "A trend needs a baseline to be real", citation: "SME guidance — trend vs baseline", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["a metric move is only a trend against a stated baseline/period", "missing the baseline means the drift is unproven"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-WKY-NOISE", type: "gov_sme_guidance", title: "Distinguishing signal from weekly noise", citation: "SME guidance — signal vs noise", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["one or two weeks of movement can be noise", "need enough periods to confirm a real trend"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-WKY-SEASONAL", type: "gov_sme_guidance", title: "Seasonal adjustment of a weekly trend", citation: "SME guidance — seasonality in trends", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["a seasonal dip can look like a decline", "adjust for season before concluding a real trend"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-WKY-COMPLIANCE", type: "regulatory_summary", title: "Compliance boundary in a trend response", citation: "regulatory summary — trend-response compliance boundary", accessedDate: ACCESSED, geography: "global", businessCategory: "regulated-SMB", reliability: "high", completeness: "medium", factsUsed: ["some trend responses (pricing/tax/labour/claims) cross a professional-review line", "OpsIQ prepares, does not give final advice"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "not_required", privacyRisk: "low" }),
  s({ id: "SRC-WKY-FRAUD", type: "failure_postmortem", title: "Gamed / misreported trend numbers", citation: "fraud post-mortem — manipulated weekly metrics", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "medium", factsUsed: ["a trend built on gamed or misreported numbers must be blocked, not acted on", "unverifiable proof is no proof"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-WKY-ROUTINE", type: "case_study", title: "Routine within-band weekly correction", citation: "controls case — routine trend correction under SOP", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "high", factsUsed: ["a small within-band correction with verified data + an SOP grant proceeds with proof"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-WKY-COGS", type: "finance_example", title: "Cost-of-goods drift within a product line", citation: "finance example — COGS creep", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "high", completeness: "medium", factsUsed: ["input-cost creep erodes margin before price is adjusted", "confirm the true cost of goods"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-WKY-PRICING", type: "finance_example", title: "Pricing / discount leakage trend", citation: "finance example — discount-leak trend", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "medium", completeness: "medium", factsUsed: ["creeping discounts leak margin over weeks", "material price changes are an owner call"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-WKY-CAPACITY", type: "sector_example", title: "Throughput / capacity trend", citation: "sector example — throughput drift", accessedDate: ACCESSED, geography: "global", businessCategory: "trades-repair-manufacturing", reliability: "high", completeness: "medium", factsUsed: ["a falling throughput trend is a capacity/scheduling constraint", "relieve the bottleneck before adding load"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-WKY-CHURN", type: "review_complaint_pattern", title: "Churn / cohort-retention analytics", citation: "retention summary — churn cohort trend", accessedDate: ACCESSED, geography: "global", businessCategory: "retail-services", reliability: "medium", completeness: "medium", factsUsed: ["churn shows in cohort retention before it shows in revenue", "needs the cohort data to confirm"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "anonymized", privacyRisk: "low" }),
  s({ id: "SRC-WKY-CONSUMABLE", type: "staffing_ops", title: "Consumable usage benchmark per job", citation: "operations summary — consumable-per-job benchmark", accessedDate: ACCESSED, geography: "global", businessCategory: "trades-repair-manufacturing", reliability: "medium", completeness: "medium", factsUsed: ["usage per job has a benchmark band", "drift above band signals waste or misuse"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-WKY-CAMPAIGN", type: "business_blog", title: "Marketing campaign ROI review", citation: "marketing summary — campaign ROI review", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "medium", completeness: "medium", factsUsed: ["a campaign's ROI needs attribution before scaling spend", "cutting or scaling spend is a material owner call"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-WKY-QUALITY", type: "staffing_ops", title: "Quality / defect-rate benchmark", citation: "operations summary — defect-rate benchmark", accessedDate: ACCESSED, geography: "global", businessCategory: "trades-repair-manufacturing", reliability: "high", completeness: "medium", factsUsed: ["defect/rework rate has an acceptable band", "a rising defect trend must be fixed before growth"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
  s({ id: "SRC-WKY-REVIEW", type: "case_study", title: "Weekly management review cadence", citation: "controls case — weekly review cadence", accessedDate: ACCESSED, geography: "global", businessCategory: "SMB-general", reliability: "high", completeness: "high", factsUsed: ["a weekly review reads trends and routes each to the right disposition", "routine within-band items proceed, material ones go to the owner"], factsInferred: [], factsSyntheticallyVaried: [], anonymizationStatus: "no_personal_data", privacyRisk: "low" }),
];

export const WEEKLY_MANAGEMENT_TREND_SOURCE_BY_ID: Record<string, SourceRecord> = Object.fromEntries(
  WEEKLY_MANAGEMENT_TREND_SOURCES.map((r) => [r.id, r]),
);
