import type { CapabilityName } from "@/domain/constants/capabilities";
import { CAPABILITIES } from "@/domain/constants/capabilities";
import { ROLES, ROLE_HIERARCHY, type RoleName } from "@/domain/constants/roles";
import { ForbiddenError } from "@/infra/errors";

const ROLE_CAPABILITIES: Record<RoleName, readonly CapabilityName[]> = {
  [ROLES.SYSTEM_ADMIN]: Object.values(CAPABILITIES),
  [ROLES.PRINCIPAL_CONSULTANT]: [
    CAPABILITIES.USER_VIEW,
    CAPABILITIES.USER_CREATE,
    CAPABILITIES.USER_UPDATE,
    CAPABILITIES.USER_ASSIGN_ROLE,
    CAPABILITIES.CLIENT_CREATE,
    CAPABILITIES.CLIENT_UPDATE,
    CAPABILITIES.CLIENT_VIEW,
    CAPABILITIES.CLIENT_ARCHIVE,
    CAPABILITIES.ENGAGEMENT_CREATE,
    CAPABILITIES.ENGAGEMENT_UPDATE,
    CAPABILITIES.ENGAGEMENT_VIEW,
    CAPABILITIES.ENGAGEMENT_MANAGE_MEMBERS,
    CAPABILITIES.STAGE_CREATE,
    CAPABILITIES.STAGE_TRANSITION,
    CAPABILITIES.STAGE_VIEW,
    CAPABILITIES.EVIDENCE_SUBMIT,
    CAPABILITIES.EVIDENCE_VALIDATE,
    CAPABILITIES.EVIDENCE_VIEW,
    CAPABILITIES.FINDING_CREATE,
    CAPABILITIES.FINDING_UPDATE,
    CAPABILITIES.FINDING_VIEW,
    CAPABILITIES.RECOMMENDATION_CREATE,
    CAPABILITIES.RECOMMENDATION_APPROVE,
    CAPABILITIES.RECOMMENDATION_VIEW,
    CAPABILITIES.ACTION_CREATE,
    CAPABILITIES.ACTION_UPDATE,
    CAPABILITIES.ACTION_VIEW,
    CAPABILITIES.KPI_DEFINE,
    CAPABILITIES.KPI_RECORD,
    CAPABILITIES.KPI_VIEW,
    CAPABILITIES.DELIVERABLE_CREATE,
    CAPABILITIES.DELIVERABLE_SUBMIT_VERSION,
    CAPABILITIES.DELIVERABLE_APPROVE,
    CAPABILITIES.DELIVERABLE_VIEW,
    CAPABILITIES.APPROVAL_REQUEST,
    CAPABILITIES.APPROVAL_DECIDE,
    CAPABILITIES.OVERRIDE_REQUEST,
    CAPABILITIES.OVERRIDE_DECIDE,
    CAPABILITIES.CONDITION_ASSESS,
    CAPABILITIES.CONDITION_VIEW,
    CAPABILITIES.INTERVENTION_MANAGE,
    CAPABILITIES.INTERVENTION_VIEW,
    CAPABILITIES.RISK_MANAGE,
    CAPABILITIES.RISK_VIEW,
    CAPABILITIES.SCOPE_MANAGE,
    CAPABILITIES.SCOPE_VIEW,
    CAPABILITIES.REVIEW_MANAGE,
    CAPABILITIES.REVIEW_VIEW,
    CAPABILITIES.FILE_UPLOAD,
    CAPABILITIES.FILE_VIEW,
    CAPABILITIES.FILE_DELETE,
  ],
  [ROLES.SENIOR_CONSULTANT]: [
    CAPABILITIES.USER_VIEW,
    CAPABILITIES.CLIENT_VIEW,
    CAPABILITIES.CLIENT_UPDATE,
    CAPABILITIES.ENGAGEMENT_CREATE,
    CAPABILITIES.ENGAGEMENT_UPDATE,
    CAPABILITIES.ENGAGEMENT_VIEW,
    CAPABILITIES.STAGE_CREATE,
    CAPABILITIES.STAGE_TRANSITION,
    CAPABILITIES.STAGE_VIEW,
    CAPABILITIES.EVIDENCE_SUBMIT,
    CAPABILITIES.EVIDENCE_VALIDATE,
    CAPABILITIES.EVIDENCE_VIEW,
    CAPABILITIES.FINDING_CREATE,
    CAPABILITIES.FINDING_UPDATE,
    CAPABILITIES.FINDING_VIEW,
    CAPABILITIES.RECOMMENDATION_CREATE,
    CAPABILITIES.RECOMMENDATION_VIEW,
    CAPABILITIES.ACTION_CREATE,
    CAPABILITIES.ACTION_UPDATE,
    CAPABILITIES.ACTION_VIEW,
    CAPABILITIES.KPI_DEFINE,
    CAPABILITIES.KPI_RECORD,
    CAPABILITIES.KPI_VIEW,
    CAPABILITIES.DELIVERABLE_CREATE,
    CAPABILITIES.DELIVERABLE_SUBMIT_VERSION,
    CAPABILITIES.DELIVERABLE_VIEW,
    CAPABILITIES.APPROVAL_REQUEST,
    CAPABILITIES.CONDITION_ASSESS,
    CAPABILITIES.CONDITION_VIEW,
    CAPABILITIES.INTERVENTION_VIEW,
    CAPABILITIES.RISK_MANAGE,
    CAPABILITIES.RISK_VIEW,
    CAPABILITIES.SCOPE_VIEW,
    CAPABILITIES.REVIEW_VIEW,
    CAPABILITIES.FILE_UPLOAD,
    CAPABILITIES.FILE_VIEW,
  ],
  [ROLES.CONSULTANT]: [
    CAPABILITIES.USER_VIEW,
    CAPABILITIES.CLIENT_VIEW,
    CAPABILITIES.ENGAGEMENT_VIEW,
    CAPABILITIES.STAGE_VIEW,
    CAPABILITIES.STAGE_TRANSITION,
    CAPABILITIES.EVIDENCE_SUBMIT,
    CAPABILITIES.EVIDENCE_VIEW,
    CAPABILITIES.FINDING_CREATE,
    CAPABILITIES.FINDING_VIEW,
    CAPABILITIES.RECOMMENDATION_VIEW,
    CAPABILITIES.ACTION_CREATE,
    CAPABILITIES.ACTION_UPDATE,
    CAPABILITIES.ACTION_VIEW,
    CAPABILITIES.KPI_VIEW,
    CAPABILITIES.DELIVERABLE_VIEW,
    CAPABILITIES.DELIVERABLE_SUBMIT_VERSION,
    CAPABILITIES.CONDITION_VIEW,
    CAPABILITIES.INTERVENTION_VIEW,
    CAPABILITIES.RISK_VIEW,
    CAPABILITIES.SCOPE_VIEW,
    CAPABILITIES.REVIEW_VIEW,
    CAPABILITIES.FILE_UPLOAD,
    CAPABILITIES.FILE_VIEW,
  ],
  [ROLES.ANALYST]: [
    CAPABILITIES.USER_VIEW,
    CAPABILITIES.CLIENT_VIEW,
    CAPABILITIES.ENGAGEMENT_VIEW,
    CAPABILITIES.STAGE_VIEW,
    CAPABILITIES.EVIDENCE_SUBMIT,
    CAPABILITIES.EVIDENCE_VIEW,
    CAPABILITIES.FINDING_VIEW,
    CAPABILITIES.RECOMMENDATION_VIEW,
    CAPABILITIES.ACTION_VIEW,
    CAPABILITIES.KPI_VIEW,
    CAPABILITIES.KPI_RECORD,
    CAPABILITIES.DELIVERABLE_VIEW,
    CAPABILITIES.CONDITION_VIEW,
    CAPABILITIES.RISK_VIEW,
    CAPABILITIES.FILE_UPLOAD,
    CAPABILITIES.FILE_VIEW,
  ],
  [ROLES.CLIENT_OWNER]: [
    CAPABILITIES.ENGAGEMENT_VIEW,
    CAPABILITIES.STAGE_VIEW,
    CAPABILITIES.EVIDENCE_VIEW,
    CAPABILITIES.FINDING_VIEW,
    CAPABILITIES.RECOMMENDATION_VIEW,
    CAPABILITIES.ACTION_VIEW,
    CAPABILITIES.KPI_VIEW,
    CAPABILITIES.DELIVERABLE_VIEW,
    CAPABILITIES.DELIVERABLE_APPROVE,
    CAPABILITIES.APPROVAL_DECIDE,
    CAPABILITIES.CONDITION_VIEW,
    CAPABILITIES.INTERVENTION_VIEW,
    CAPABILITIES.RISK_VIEW,
    CAPABILITIES.SCOPE_VIEW,
    CAPABILITIES.FILE_VIEW,
  ],
  [ROLES.CLIENT_STAKEHOLDER]: [
    CAPABILITIES.ENGAGEMENT_VIEW,
    CAPABILITIES.STAGE_VIEW,
    CAPABILITIES.EVIDENCE_VIEW,
    CAPABILITIES.FINDING_VIEW,
    CAPABILITIES.RECOMMENDATION_VIEW,
    CAPABILITIES.ACTION_VIEW,
    CAPABILITIES.KPI_VIEW,
    CAPABILITIES.DELIVERABLE_VIEW,
    CAPABILITIES.FILE_VIEW,
  ],
  [ROLES.VIEWER]: [
    CAPABILITIES.ENGAGEMENT_VIEW,
    CAPABILITIES.STAGE_VIEW,
    CAPABILITIES.KPI_VIEW,
    CAPABILITIES.DELIVERABLE_VIEW,
  ],
};

export interface PolicyContext {
  userId: string;
  roles: Array<{
    role: RoleName;
    scope?: string | null;
    scopeId?: string | null;
  }>;
}

export function hasCapability(
  ctx: PolicyContext,
  capability: CapabilityName,
  scope?: { type: string; id: string }
): boolean {
  for (const assignment of ctx.roles) {
    const caps = ROLE_CAPABILITIES[assignment.role];
    if (!caps) continue;

    if (!caps.includes(capability)) continue;

    if (!scope) return true;

    if (!assignment.scope) return true;

    if (
      assignment.scope === scope.type &&
      assignment.scopeId === scope.id
    ) {
      return true;
    }
  }

  return false;
}

export function requireCapability(
  ctx: PolicyContext,
  capability: CapabilityName,
  scope?: { type: string; id: string }
): void {
  if (!hasCapability(ctx, capability, scope)) {
    throw new ForbiddenError(
      `Missing required capability: ${capability}`
    );
  }
}

export function highestRole(ctx: PolicyContext): RoleName | null {
  let highest: RoleName | null = null;
  let highestLevel = -1;

  for (const assignment of ctx.roles) {
    const level = ROLE_HIERARCHY[assignment.role] ?? 0;
    if (level > highestLevel) {
      highestLevel = level;
      highest = assignment.role;
    }
  }

  return highest;
}
